// Hand-written clues for the short, high-traffic fill that shows up in almost
// every puzzle. These take priority over the dictionary-derived fallbacks, so
// the micro and mini grids read like a person wrote them.
export const CURATED = {
  // --- three letters ---
  ACE: ["Serve that never comes back", "Card above a king", "Nail, as an exam"],
  ACT: ["Part of a play", "Do something", "Put on a show"],
  ADD: ["Toss in", "Do some arithmetic", "Sum up"],
  ADO: ["Fuss", "Much ___ About Nothing", "Commotion"],
  AGE: ["Number of candles", "Get older", "Ice ___"],
  AGO: ["In the past", "Long ___", "Back when"],
  AID: ["Help out", "First ___ kit", "Assistance"],
  AIM: ["Point a camera", "Goal", "Take careful ___"],
  AIR: ["What a tire holds", "Broadcast", "Fresh ___"],
  ALE: ["Pub pour", "Pale ___", "Brew with hops"],
  ALL: ["Every last bit", "___ or nothing", "The whole lot"],
  AMP: ["Guitarist's plug-in", "Current unit", "___ it up"],
  ANT: ["Picnic crasher", "Colony member", "Tiny worker"],
  APE: ["Gorilla, for one", "Mimic", "Zoo swinger"],
  APT: ["Fitting", "Likely to", "Well-chosen"],
  ARC: ["Curved path", "Rainbow shape", "Story ___"],
  ARE: ["You ___ here", "Exist, in the plural", "Third of a hectare"],
  ARK: ["Noah's boat", "Vessel with pairs", "Raiders of the Lost ___"],
  ARM: ["Sleeve filler", "Branch of the military", "Long ___ of the law"],
  ART: ["Museum contents", "Gallery hanging", "Fine ___"],
  ASH: ["Fireplace leftovers", "Tree with tough wood", "Cigarette residue"],
  ASK: ["Pose a question", "Big ___", "Inquire"],
  ATE: ["Had dinner", "Consumed", "Devoured"],
  AWE: ["Shock and ___", "Wonderment", "Leave speechless"],
  AXE: ["Chopping tool", "Guitar, in slang", "Cut, as a program"],
  BAD: ["Not good", "Rotten", "Michael Jackson album"],
  BAG: ["Grocery carrier", "Catch, as game", "Under-eye problem"],
  BAN: ["Forbid", "Prohibition", "Boot from the server"],
  BAR: ["Where drinks are poured", "Block, as a door", "Candy ___"],
  BAT: ["Cave flier", "Swing it at a ball", "Louisville Slugger"],
  BAY: ["Coastal inlet", "Sick ___", "Hound's cry"],
  BED: ["Sleeping spot", "Flower plot", "Truck's back"],
  BEE: ["Spelling contest", "Hive dweller", "Busy as a ___"],
  BEG: ["Plead", "What a good dog does", "Ask on your knees"],
  BET: ["Wager", "Safe ___", "Casino action"],
  BID: ["Auction offer", "Bridge call", "Make an offer"],
  BIG: ["Large", "Tom Hanks movie", "Not small"],
  BIN: ["Recycling receptacle", "Storage box", "Bargain ___"],
  BIT: ["Small piece", "Comedy routine", "Byte fraction"],
  BOA: ["Feathery scarf", "Squeezing snake", "Constrictor"],
  BOG: ["Marshy ground", "___ down", "Peat source"],
  BOO: ["Ghost's greeting", "Crowd's jeer", "Sweetheart, in slang"],
  BOW: ["Archer's tool", "Take a ___", "Ship's front"],
  BOX: ["Cardboard container", "Spar in a ring", "Penalty ___"],
  BOY: ["Lad", "Oh, ___!", "Young fellow"],
  BUD: ["Flower-to-be", "Pal", "Taste ___"],
  BUG: ["Software flaw", "Beetle, e.g.", "Pester"],
  BUN: ["Burger holder", "Hair knot", "Cinnamon ___"],
  BUS: ["School transport", "Clear tables", "City ride"],
  BUY: ["Purchase", "Believe, informally", "Good ___"],
  CAB: ["Yellow ride", "Truck's front", "Hail one in the city"],
  CAN: ["Soda container", "Be able to", "Preserve, as peaches"],
  CAP: ["Baseball topper", "Upper limit", "Bottle closer"],
  CAR: ["Garage occupant", "Train unit", "Sedan or coupe"],
  CAT: ["Nine-lived pet", "Lion or tiger", "Curiosity victim"],
  COB: ["Corn holder", "Male swan", "Sweet corn support"],
  COD: ["Fish and chips fish", "Cape ___", "Atlantic catch"],
  COG: ["Gear tooth", "Small part of a machine", "Wheel projection"],
  COO: ["Pigeon sound", "Speak lovingly", "Baby noise"],
  COP: ["Officer on the beat", "___ a plea", "Badge wearer"],
  COT: ["Camping bed", "Folding sleeper", "Army bunk"],
  COW: ["Barn resident", "Intimidate", "Milk source"],
  CRY: ["Shed tears", "Battle ___", "Far ___ from"],
  CUB: ["Bear youngster", "Scout", "Chicago ballplayer"],
  CUE: ["Pool stick", "Signal to start", "On ___"],
  CUP: ["Mug's cousin", "World ___", "Coffee holder"],
  CUT: ["Slice", "Reduce", "Director's call"],
  DAM: ["River blocker", "Beaver's project", "Hoover ___"],
  DAY: ["24 hours", "___ off", "Sun's shift"],
  DEN: ["Cozy room", "Lion's home", "Study"],
  DEW: ["Morning moisture", "Grass droplets", "Mountain ___"],
  DIE: ["Cube with pips", "Perish", "___ hard"],
  DIG: ["Excavate", "Archaeologist's site", "Subtle insult"],
  DIM: ["Not bright", "Lower the lights", "Faint"],
  DIP: ["Chips accompaniment", "Quick swim", "Slight drop"],
  DOE: ["Female deer", "Fawn's mom", "___, a deer"],
  DOG: ["Loyal pet", "Hound", "Tail wagger"],
  DOT: ["Period", "Morse mark", "Polka ___"],
  DRY: ["Not wet", "Sahara-like", "Sense of humor type"],
  DUE: ["Owed", "Expected", "Give the devil his ___"],
  DUO: ["Twosome", "Pair of performers", "Dynamic ___"],
  DYE: ["Change a shirt's color", "Tint", "Hair treatment"],
  EAR: ["Corn unit", "Hearing organ", "Lend an ___"],
  EAT: ["Have a meal", "Dig in", "Consume"],
  EBB: ["Tide's retreat", "Flow's partner", "Decline"],
  EEL: ["Slippery swimmer", "Sushi bar order", "Electric fish"],
  EGG: ["Breakfast staple", "Nest item", "___ on"],
  EGO: ["Sense of self", "Id neighbor", "Big ___"],
  ELF: ["Santa's helper", "Tolkien creature", "Shelf sitter"],
  ELK: ["Antlered animal", "Lodge member", "Big deer"],
  ELM: ["Shade tree", "Street of nightmares", "Dutch ___ disease"],
  EMU: ["Flightless bird", "Ostrich cousin", "Australian runner"],
  END: ["Finish", "The ___", "Tail end"],
  EON: ["Very long time", "Geologic age", "Ages and ages"],
  ERA: ["Historical period", "Pitcher's stat", "Age"],
  EVE: ["Night before", "Adam's partner", "New Year's ___"],
  EWE: ["Female sheep", "Lamb's mother", "Flock member"],
  EYE: ["Needle opening", "Storm's calm center", "Keep an ___ on"],
  FAD: ["Passing craze", "Short-lived trend", "Hula hoop, once"],
  FAN: ["Cooling device", "Devoted follower", "Spread out"],
  FAR: ["Distant", "___ and away", "Not near"],
  FAT: ["Chunky", "Nutrition label line", "___ chance"],
  FEE: ["Charge", "Cover ___", "Service cost"],
  FEW: ["Not many", "A ___ good men", "Handful"],
  FIB: ["Little lie", "Tell a whopper", "Untruth"],
  FIG: ["Newton's fruit", "Leaf on a statue", "Dried snack"],
  FIN: ["Shark's giveaway", "Five-spot", "Swimmer's blade"],
  FIR: ["Christmas tree option", "Evergreen", "Conifer"],
  FIT: ["In shape", "Tantrum", "Suitable"],
  FIX: ["Repair", "Jam", "Set firmly"],
  FLU: ["Winter bug", "Shot target", "Seasonal illness"],
  FLY: ["Soar", "Picnic pest", "Zipper's cover"],
  FOE: ["Enemy", "Opponent", "Rival"],
  FOG: ["Low cloud", "Mental haze", "Airport delayer"],
  FOX: ["Sly one", "Henhouse threat", "Red-furred canine"],
  FRY: ["Cook in oil", "Small ___", "Diner side, singularly"],
  FUN: ["A good time", "Enjoyable", "Poke ___ at"],
  FUR: ["Cat's coat", "Pelt", "Winter coat material"],
  GAP: ["Opening", "Generation ___", "Space between"],
  GAS: ["Pump purchase", "Step on it", "Natural ___"],
  GEL: ["Hair product", "Come together", "Firm up"],
  GEM: ["Precious stone", "Real find", "Jewel"],
  GNU: ["African antelope", "Wildebeest", "Zoo grazer"],
  GUM: ["Chew it", "Bubble maker", "Sticky stuff"],
  GUT: ["Instinct", "Belly", "Strip bare"],
  GYM: ["Workout spot", "PE class", "Where the weights are"],
  HAM: ["Deli meat", "Overactor", "Radio operator"],
  HAT: ["Head cover", "Trick topper", "Cap or beret"],
  HAY: ["Barn bale", "Make ___ while the sun shines", "Horse feed"],
  HEN: ["Egg layer", "Coop resident", "Female chicken"],
  HEW: ["Chop with an axe", "Cut down", "Shape roughly"],
  HIP: ["Trendy", "Joint replaced", "___ hooray"],
  HIT: ["Chart-topper", "Strike", "Bases-earning swing"],
  HOE: ["Garden tool", "Weeding implement", "Break up soil"],
  HOG: ["Pig", "Take more than your share", "Road ___"],
  HOP: ["Jump on one foot", "Short flight", "Beer ingredient"],
  HOT: ["Sizzling", "In demand", "Not cold"],
  HUB: ["Wheel's center", "Airline base", "Focal point"],
  HUE: ["Shade of color", "Tint", "___ and cry"],
  HUG: ["Warm embrace", "Squeeze fondly", "Bear ___"],
  HUM: ["Wordless tune", "Bee sound", "Buzz along"],
  HUT: ["Simple shelter", "Pizza ___", "Quarterback's call"],
  ICE: ["Frozen water", "Skater's surface", "Cake topping"],
  ICY: ["Slick, as a road", "Cold as can be", "Frosty"],
  ILL: ["Under the weather", "Sick", "Speak ___ of"],
  IMP: ["Little mischief-maker", "Bratty sprite", "Pixie"],
  INK: ["Pen filler", "Tattoo", "Sign a deal"],
  INN: ["Roadside lodging", "Holiday ___", "Traveler's rest"],
  ION: ["Charged particle", "Chemistry class subject", "Anion or cation"],
  IRE: ["Anger", "Wrath", "Draw the ___ of"],
  IRK: ["Annoy", "Get under one's skin", "Bug"],
  IVY: ["Climbing vine", "League with Yale", "Poison ___"],
  JAB: ["Boxer's quick punch", "Poke", "Verbal dig"],
  JAM: ["Toast spread", "Traffic snarl", "Improvise together"],
  JAR: ["Pickle holder", "Jolt", "Mason ___"],
  JAW: ["Chin's home", "Chatter", "Lower ___"],
  JET: ["Airliner", "Deep black", "Shoot out forcefully"],
  JIG: ["Lively dance", "The ___ is up", "Irish tune"],
  JOB: ["Day gig", "Employment", "Task"],
  JOG: ["Easy run", "Nudge the memory", "Trot"],
  JOT: ["Write quickly", "Tiny amount", "___ down"],
  JOY: ["Great gladness", "Delight", "___ ride"],
  JUG: ["Milk container", "Pitcher", "Big jar"],
  KEG: ["Party barrel", "Beer container", "Tapped vessel"],
  KEY: ["Lock opener", "Piano part", "Crucial"],
  KID: ["Youngster", "Tease", "Baby goat"],
  KIN: ["Relatives", "Next of ___", "Family"],
  KIT: ["Set of tools", "First aid ___", "Drum ___"],
  LAB: ["Research room", "Retriever breed", "Where experiments happen"],
  LAD: ["Young man", "Boy", "Fellow"],
  LAG: ["Fall behind", "Network delay", "Jet ___"],
  LAP: ["Track circuit", "Seated surface", "Drink like a cat"],
  LAW: ["Rule of the land", "Murphy's ___", "Legal system"],
  LEG: ["Table support", "Race segment", "Limb"],
  LID: ["Jar topper", "Eye cover", "Put a ___ on it"],
  LIE: ["Untruth", "Recline", "___ low"],
  LIP: ["Cup's edge", "Sass", "Mouth border"],
  LOB: ["High tennis shot", "Toss gently", "Arc a ball"],
  LOG: ["Fireplace fuel", "Keep a record", "Captain's record"],
  LOT: ["Parking area", "Great deal", "Auction item"],
  LOW: ["Not high", "Cattle sound", "Bottom of the range"],
  MAD: ["Angry", "___ as a hatter", "Magazine of satire"],
  MAP: ["Road guide", "Chart out", "Atlas page"],
  MAT: ["Doormat", "Wrestling surface", "Tangle up"],
  MIX: ["Blend", "Playlist", "Stir together"],
  MOB: ["Unruly crowd", "Swarm around", "Organized crime group"],
  MOP: ["Floor cleaner", "___ up", "Shaggy hair"],
  MUD: ["Wet dirt", "Sling it in politics", "Pig's bath"],
  MUG: ["Coffee cup", "Make faces", "Rob on the street"],
  NAG: ["Pester", "Old horse", "Keep after"],
  NAP: ["Short sleep", "Cat ___", "Afternoon rest"],
  NET: ["Tennis divider", "After deductions", "Catch"],
  NEW: ["Brand ___", "Fresh", "Just out"],
  NIL: ["Nothing", "Zero, in soccer", "Zilch"],
  NIP: ["Small bite", "Chill in the air", "___ it in the bud"],
  NOD: ["Yes signal", "Doze off", "Approval gesture"],
  NUN: ["Convent resident", "Sister", "One in a habit"],
  NUT: ["Bolt's partner", "Almond or pecan", "Enthusiast"],
  OAK: ["Acorn tree", "Sturdy wood", "Barrel material"],
  OAR: ["Rowboat mover", "Paddle", "Crew tool"],
  OAT: ["Cereal grain", "___ milk", "Horse feed"],
  ODD: ["Strange", "Not even", "Peculiar"],
  ODE: ["Poem of praise", "Keats work", "___ to Joy"],
  OIL: ["Salad dressing base", "Crude export", "Engine fluid"],
  OLD: ["Aged", "Not new", "___ hat"],
  ONE: ["Number of noses", "Single", "The loneliest number"],
  OPT: ["Choose", "___ out", "Make a selection"],
  ORB: ["Sphere", "Globe", "Heavenly body"],
  ORE: ["Mine find", "Iron source", "Raw material"],
  OUR: ["Belonging to us", "___ house", "Yours and mine"],
  OUT: ["Not in", "Baseball call", "Way ___"],
  OWE: ["Be in debt", "Have to pay back", "Be obliged"],
  OWL: ["Night bird", "Wise one", "Hooter"],
  OWN: ["Possess", "Admit, with up", "Have title to"],
  PAD: ["Notepad", "Apartment", "Launch platform"],
  PAL: ["Buddy", "Friend", "Chum"],
  PAN: ["Frying vessel", "Review harshly", "Camera sweep"],
  PAR: ["Golf standard", "Up to ___", "Average"],
  PAW: ["Animal foot", "Handle roughly", "Cat's mitt"],
  PEA: ["Pod dweller", "Green sphere", "Princess's problem"],
  PEG: ["Cribbage marker", "Coat hook", "Square ___ in a round hole"],
  PEN: ["Ink holder", "Write", "Pig's enclosure"],
  PET: ["Dog or cat", "Stroke gently", "Teacher's ___"],
  PIE: ["Dessert with a crust", "Easy as ___", "Chart type"],
  PIG: ["Farm oinker", "Guinea ___", "Mud lover"],
  PIN: ["Bowling target", "Fasten", "Sewing spike"],
  PIT: ["Peach center", "Racing stop", "Deep hole"],
  POD: ["Whale group", "Pea holder", "Coffee ___"],
  POP: ["Soda", "Music genre", "Burst"],
  POT: ["Cooking vessel", "Poker stakes", "Planter"],
  PRO: ["Expert", "Not an amateur", "___ and con"],
  PRY: ["Snoop", "Lever open", "Be nosy"],
  PUB: ["Local watering hole", "British bar", "Where darts are thrown"],
  PUN: ["Wordplay", "Groan-worthy joke", "Play on words"],
  PUP: ["Young dog", "___ tent", "Litter member"],
  PUT: ["Place", "___ off", "Set down"],
  RAG: ["Cleaning cloth", "Tabloid", "Scott Joplin tune"],
  RAM: ["Male sheep", "Computer memory", "Crash into"],
  RAP: ["Music genre", "Knock", "Take the ___"],
  RAT: ["Rodent", "Informant", "___ race"],
  RAW: ["Uncooked", "Unprocessed", "Sushi-grade"],
  RAY: ["Beam of light", "Manta ___", "Sunbeam"],
  RED: ["Stop sign color", "In the ___", "Fire truck hue"],
  RIB: ["Chest bone", "Tease", "BBQ order"],
  RID: ["Get ___ of", "Free from", "Clear away"],
  RIG: ["Oil platform", "Set up", "Big truck"],
  RIM: ["Basketball hoop part", "Wheel edge", "Cup's lip"],
  RIP: ["Tear", "___ current", "Shred"],
  ROB: ["Hold up", "Steal from", "Burgle"],
  ROD: ["Fishing pole", "Curtain holder", "Hot ___"],
  ROT: ["Decay", "Nonsense", "Spoil"],
  ROW: ["Boat with oars", "Line of seats", "Heated argument"],
  RUB: ["Massage", "There's the ___", "Chafe"],
  RUE: ["Regret", "Bitter herb", "Wish undone"],
  RUG: ["Floor covering", "Persian ___", "Sweep it under the ___"],
  RUN: ["Sprint", "Manage", "Stocking flaw"],
  RUT: ["Wheel groove", "Stuck in a ___", "Boring routine"],
  RYE: ["Deli bread", "Whiskey grain", "Catcher in the ___"],
  SAD: ["Blue", "Down in the dumps", "Tearjerker's effect"],
  SAG: ["Droop", "Sink in the middle", "Lose firmness"],
  SAP: ["Maple syrup source", "Drain the energy of", "Gullible sort"],
  SAW: ["Cutting tool", "Old adage", "Laid eyes on"],
  SEA: ["Ocean", "Dead ___", "Salt water"],
  SEE: ["Spot", "Understand", "Wait and ___"],
  SET: ["Tennis unit", "Put in place", "Movie backdrop"],
  SEW: ["Use a needle", "Stitch up", "Tailor's task"],
  SHY: ["Bashful", "Timid", "Just ___ of"],
  SIP: ["Small drink", "Taste slowly", "Nurse a drink"],
  SIR: ["Knight's title", "Polite address", "Yes, ___"],
  SIT: ["Take a seat", "Babysit", "Stay put"],
  SIX: ["Half a dozen", "Number of sides on a die", "Deep ___"],
  SKI: ["Slope activity", "Snow runner", "Water ___"],
  SKY: ["Blue expanse", "___ high", "Where clouds are"],
  SLY: ["Crafty", "Foxlike", "On the ___"],
  SOB: ["Cry hard", "___ story", "Weep"],
  SOD: ["Lawn square", "Turf", "Ground cover"],
  SON: ["Male offspring", "Junior", "Prodigal ___"],
  SOY: ["Sushi sauce", "Tofu source", "Bean in miso"],
  SPA: ["Massage destination", "Hot tub retreat", "Day of pampering"],
  SPY: ["Secret agent", "Catch sight of", "I ___"],
  SUB: ["Sandwich", "Fill in", "Underwater vessel"],
  SUE: ["Take to court", "File a claim against", "Litigate"],
  SUM: ["Total", "Add up", "In ___"],
  SUN: ["Solar system center", "Beach draw", "Source of a tan"],
  TAB: ["Bar bill", "Browser feature", "Keyboard key"],
  TAG: ["Playground game", "Price label", "You're it"],
  TAN: ["Beach souvenir", "Light brown", "Sun result"],
  TAP: ["Faucet", "Light knock", "Dance style"],
  TAR: ["Road sealant", "Sticky black stuff", "Pitch"],
  TAX: ["April obligation", "Strain", "Levy"],
  TEA: ["Afternoon brew", "Green or black", "Cup contents"],
  TEE: ["Golf peg", "Shirt", "___ time"],
  TEN: ["Perfect score", "Digit count", "Bowling pin number"],
  TIC: ["Nervous twitch", "Involuntary habit", "Small spasm"],
  TIE: ["Neckwear", "Deadlock", "Bind"],
  TIN: ["Cookie container", "Can metal", "Element No. 50"],
  TIP: ["Server's bonus", "Useful hint", "Iceberg's top"],
  TOE: ["Foot digit", "___ the line", "Sock's end"],
  TON: ["2,000 pounds", "Whole lot", "Heavy weight"],
  TOP: ["Highest point", "Spinning toy", "Shirt"],
  TOW: ["Haul away", "___ truck", "Pull behind"],
  TOY: ["Playroom item", "Trifle with", "Christmas gift"],
  TRY: ["Attempt", "Rugby score", "Give it a shot"],
  TUB: ["Bathroom fixture", "Ice cream container", "Soak spot"],
  TUG: ["Yank", "Harbor boat", "___ of war"],
  TWO: ["Pair", "Number of shoes", "It takes ___"],
  URN: ["Coffee dispenser", "Grecian vessel", "Ashes holder"],
  USE: ["Put to work", "Employ", "No ___ crying"],
  VAN: ["Moving vehicle", "Minibus", "Delivery ride"],
  VAT: ["Big brewing tub", "Wine container", "Dye tank"],
  VET: ["Animal doctor", "Check thoroughly", "Ex-soldier"],
  VIA: ["By way of", "Through", "Traveling by"],
  VIE: ["Compete", "Contend", "Go head to head"],
  VOW: ["Solemn promise", "Wedding words", "Pledge"],
  WAG: ["Move like a tail", "Joker", "Shake to and fro"],
  WAR: ["Armed conflict", "Card game", "Tug of ___"],
  WAX: ["Candle material", "Grow, as the moon", "Ear stuff"],
  WEB: ["Spider's work", "Internet", "Tangled ___"],
  WED: ["Get married", "Tie the knot", "Middle of the week, briefly"],
  WEE: ["Tiny", "___ hours", "Very small"],
  WET: ["Soaked", "Not dry", "Rainy"],
  WIG: ["Hairpiece", "Toupee", "Courtroom headwear, in Britain"],
  WIN: ["Come in first", "Victory", "Take the prize"],
  WIT: ["Clever humor", "Quick ___", "Sharp mind"],
  WOE: ["Sorrow", "___ is me", "Deep trouble"],
  WOK: ["Stir-fry pan", "Asian cookware", "Round-bottomed pan"],
  WOO: ["Court romantically", "Pursue", "Win over"],
  YAK: ["Tibetan ox", "Chatter", "Shaggy bovine"],
  YAM: ["Sweet potato", "Thanksgiving side", "Root vegetable"],
  YEN: ["Tokyo currency", "Strong craving", "Longing"],
  YES: ["Affirmative", "Nod's meaning", "Opposite of no"],
  YET: ["So far", "Nevertheless", "Still"],
  YEW: ["Evergreen shrub", "Bow wood", "Churchyard tree"],
  ZAP: ["Microwave", "Hit with a laser", "Zing"],
  ZIP: ["Nothing at all", "Close a jacket", "Speed along"],
  ZOO: ["Animal park", "Wild scene", "Where the lions are"],
};
