// Themed answers both players get. Every entry is hand-written: the answer, and
// a clue that actually clues it. The filler prefers these over dictionary fill,
// so grids come out mostly on-theme.
//
// Answers must be A-Z only and 3-15 letters, like any other entry in the bank.

export const SHARED_THEMES = {
  "rock climbing": [
    ["BELAY", "Manage the rope for a climbing partner"],
    ["CRIMP", "Tiny edge held with the fingertips"],
    ["CHALK", "What comes out of the bag at the crag"],
    ["DYNO", "All-out jump between holds"],
    ["BETA", "Someone else's solution to a route"],
    ["SEND", "Climb it clean, at last"],
    ["CRUX", "Hardest move on the route"],
    ["SLAB", "Low-angle face climbed on friction"],
    ["JUG", "Hold you can wrap a whole hand around"],
    ["ARETE", "Outside corner of rock"],
    ["PITON", "Old-school spike hammered into a crack"],
    ["ANCHOR", "What the rope is ultimately tied to"],
    ["RAPPEL", "Descend the rope"],
    ["HARNESS", "What the rope clips into"],
    ["ONSIGHT", "Send with no falls and no beta"],
    ["TOPROPE", "Setup where the rope runs from above"],
    ["BOULDER", "Rope-free climbing, over a pad"],
    ["SLOPER", "Rounded hold with nothing to grab"],
    ["PINCH", "Hold squeezed between thumb and fingers"],
    ["POCKET", "Hold with room for a finger or two"],
    ["CHIMNEY", "Gap wide enough to climb with your back"],
    ["OVERHANG", "Rock that leans out over you"],
    ["MANTLE", "Press-down move to top out"],
    ["HEELHOOK", "Move that puts a boot above your hands"],
    ["SPOTTER", "Person guiding a boulderer's fall"],
    ["CARABINER", "Metal clip on a climber's harness"],
    ["QUICKDRAW", "Two clips joined by webbing"],
    ["PITCH", "One rope-length of a long climb"],
    ["CRAG", "Outdoor climbing spot"],
    ["GRADE", "How hard a route is said to be"],
    ["ROUTE", "Line up the wall"],
    ["FLASH", "First-try send, with beta"],
    ["PUMPED", "Forearms too full of blood to hold on"],
    ["CHOSS", "Loose, crumbling rock"],
    ["SUMMIT", "The point of going up"],
    ["ASCENT", "Trip to the top"],
    ["TRAVERSE", "Move sideways rather than up"],
    ["APPROACH", "Hike before the actual climbing"],
    ["RUNOUT", "Long, scary stretch above the last clip"],
    ["KNOT", "Figure eight, for one"],
  ],

  golf: [
    ["PAR", "What the scorecard expects"],
    ["TEE", "Peg the ball sits on"],
    ["PIN", "Flagstick"],
    ["LIE", "How the ball is sitting"],
    ["CUP", "What the ball finally drops into"],
    ["PUTT", "Stroke on the green"],
    ["CHIP", "Short lofted shot near the green"],
    ["IRON", "Numbered club"],
    ["WEDGE", "Club for getting out of sand"],
    ["DRIVER", "Big stick off the tee"],
    ["PUTTER", "Club used most on the green"],
    ["BIRDIE", "One under par"],
    ["EAGLE", "Two under par"],
    ["BOGEY", "One over par"],
    ["ALBATROSS", "Three under par"],
    ["DIVOT", "Turf you are supposed to replace"],
    ["BUNKER", "Sand trap"],
    ["FAIRWAY", "Where you meant to hit it"],
    ["ROUGH", "Long grass off the fairway"],
    ["GREEN", "Closely mown ground around the hole"],
    ["FRINGE", "Collar of grass around the green"],
    ["LINKS", "Seaside course, properly speaking"],
    ["CADDIE", "One carrying the bag"],
    ["SLICE", "Shot that curves away badly"],
    ["HOOK", "Shot that curves the other way badly"],
    ["FADE", "Gentle, intentional left-to-right shape"],
    ["SHANK", "Worst strike in the game"],
    ["FORE", "Shouted warning on the course"],
    ["MULLIGAN", "Do-over, unofficially"],
    ["GIMME", "Putt short enough to concede"],
    ["YIPS", "Twitch that ruins short putts"],
    ["DOGLEG", "Hole that bends"],
    ["HANDICAP", "Number that lets anyone play anyone"],
    ["SCRAMBLE", "Format where the team plays the best ball"],
    ["HAZARD", "Water, typically"],
    ["STANCE", "How you set your feet"],
    ["SWING", "The whole point, mechanically"],
    ["APRON", "Short grass just off the putting surface"],
    ["ROUND", "Eighteen holes"],
    ["ACE", "Hole in one"],
  ],

  reddit: [
    ["KARMA", "Points that mean nothing and everything"],
    ["UPVOTE", "Little arrow that lifts a post"],
    ["DOWNVOTE", "Little arrow that buries a post"],
    ["SUBREDDIT", "Community with its own rules and mods"],
    ["MOD", "Volunteer with the ban hammer"],
    ["AMA", "Thread where you get to ask anything"],
    ["TIL", "Post opener for a fresh fact"],
    ["OPS", "Original posters, briefly"],
    ["FLAIR", "Tag next to a username or post"],
    ["SNOO", "Reddit's alien mascot"],
    ["LURKER", "Reader who never comments"],
    ["REPOST", "You have definitely seen this before"],
    ["CROSSPOST", "Same link, second community"],
    ["THREAD", "A post and everything under it"],
    ["COMMENT", "Where the real content usually is"],
    ["TLDR", "Summary for the impatient"],
    ["WHOOSH", "Reply to someone who missed the joke"],
    ["NSFW", "Tag meaning don't open this at work"],
    ["EDIT", "Line added after the fact, often thanking strangers"],
    ["FEED", "What the front page serves you"],
    ["AWARD", "Thing people used to buy for a good comment"],
    ["RANT", "Post that is mostly shouting"],
    ["MEGATHREAD", "One post to contain the chaos"],
    ["DOWNVOTED", "Sent to the bottom of the thread"],
  ],

  memes: [
    ["MEME", "Idea that spreads because it is funny"],
    ["DOGE", "Shiba Inu with bad grammar"],
    ["LOL", "Text-speak laugh"],
    ["LMAO", "Louder text-speak laugh"],
    ["POG", "Stream-chat cry of excitement"],
    ["SUS", "Suspicious, in the game"],
    ["YEET", "Throw with maximum enthusiasm"],
    ["DANK", "Ironically excellent, meme-wise"],
    ["COPE", "What the loser is accused of doing"],
    ["BASED", "Compliment for saying the unpopular thing"],
    ["CRINGE", "The opposite of based"],
    ["VIRAL", "Spreading fast online"],
    ["TROLL", "Poster who is winding you up on purpose"],
    ["RIZZ", "Charm, per the internet"],
    ["STONKS", "Deliberately misspelled market gains"],
    ["RICKROLL", "Link that turns out to be Astley"],
    ["PEPE", "Cartoon frog of the internet"],
    ["WOJAK", "Crudely drawn feelings guy"],
    ["CHAD", "Meme archetype of effortless confidence"],
    ["SIMP", "Insult for being too nice online"],
    ["BRUH", "Single-word expression of disbelief"],
    ["SALTY", "Bitter about losing"],
    ["FLEX", "Show off, in slang"],
    ["DRIP", "Outfit worth showing off"],
    ["VIBE", "General feel of a thing"],
    ["SHEESH", "Drawn-out sound of being impressed"],
    ["EMOJI", "Little yellow face"],
    ["GOAT", "Greatest of all time, in initials"],
    ["ROFL", "Older laugh acronym"],
    ["CAPTION", "Text over the picture"],
  ],

  korea: [
    ["SEOUL", "Capital on the Han River"],
    ["BUSAN", "Korea's big port city"],
    ["KIMCHI", "Fermented cabbage on every Korean table"],
    ["SOJU", "Clear Korean spirit in a green bottle"],
    ["HANBOK", "Traditional Korean dress"],
    ["HANGUL", "Korean alphabet, invented on purpose"],
    ["KPOP", "Seoul's biggest musical export"],
    ["JEJU", "Volcanic island south of the peninsula"],
    ["BIBIMBAP", "Rice bowl you mix yourself"],
    ["BULGOGI", "Marinated grilled beef"],
    ["GIMBAP", "Seaweed rice roll, Korean style"],
    ["BANCHAN", "The little side dishes"],
    ["GANGNAM", "Seoul district with a very famous song"],
    ["INCHEON", "Airport city west of Seoul"],
    ["TAEKWONDO", "Korean martial art of kicks"],
    ["NORAEBANG", "Korean karaoke room"],
    ["HANOK", "Traditional Korean house"],
    ["ONDOL", "Underfloor heating, Korean style"],
    ["MAKGEOLLI", "Milky rice brew"],
    ["CHUSEOK", "Korean harvest holiday"],
    ["WON", "Money in Seoul"],
    ["SEJONG", "King who gave Korea its alphabet"],
    ["DAEGU", "City in Korea's southeast"],
    ["TTEOK", "Chewy Korean rice cake"],
  ],

  japan: [
    ["TOKYO", "World's largest metro area"],
    ["KYOTO", "Old capital full of temples"],
    ["OSAKA", "Japan's kitchen"],
    ["FUJI", "Japan's most photographed mountain"],
    ["YEN", "Money in Tokyo"],
    ["SUSHI", "Vinegared rice, done properly"],
    ["RAMEN", "Bowl of broth, noodles and egg"],
    ["UDON", "Thick wheat noodle"],
    ["SOBA", "Buckwheat noodle"],
    ["MISO", "Fermented soybean paste"],
    ["SAKE", "Rice wine"],
    ["WASABI", "Green heat with sushi"],
    ["MATCHA", "Powdered green tea"],
    ["BENTO", "Boxed lunch, compartmentalised"],
    ["TEMPURA", "Lightly battered and fried"],
    ["SASHIMI", "Just the fish, no rice"],
    ["ANIME", "Animation from Japan"],
    ["MANGA", "Comics read right to left"],
    ["SUMO", "Wrestling in a clay ring"],
    ["NINJA", "Shadowy operative of legend"],
    ["SAMURAI", "Sword-carrying retainer"],
    ["SHOGUN", "Military ruler of old Japan"],
    ["GEISHA", "Trained entertainer of Kyoto"],
    ["KIMONO", "Robe tied with an obi"],
    ["OBI", "Sash around a kimono"],
    ["ONSEN", "Hot spring bath"],
    ["TATAMI", "Woven straw floor mat"],
    ["ORIGAMI", "Paper folding"],
    ["HAIKU", "Seventeen syllables"],
    ["KARAOKE", "Singing to a backing track"],
    ["TORII", "Gate at the entrance to a shrine"],
    ["KOI", "Ornamental pond carp"],
    ["ZEN", "School of Buddhism big on sitting still"],
    ["DOJO", "Where martial arts are practised"],
    ["SENSEI", "The one doing the teaching"],
    ["SAKURA", "Cherry blossom"],
    ["SHIBUYA", "Tokyo district with the famous crossing"],
    ["HOKKAIDO", "Japan's northern island"],
    ["NARA", "Old capital known for its deer"],
    ["SHINKANSEN", "Bullet train"],
    ["IZAKAYA", "Japanese pub with small plates"],
    ["YAKITORI", "Grilled skewers"],
  ],

  "hong kong": [
    ["KOWLOON", "Hong Kong side facing the island"],
    ["LANTAU", "Hong Kong's largest island"],
    ["DIMSUM", "Trolley full of small plates"],
    ["WONTON", "Dumpling in soup"],
    ["EGGTART", "Custard pastry of Hong Kong bakeries"],
    ["JUNK", "Red-sailed boat in the harbour"],
    ["TRAM", "Double-decker on Hong Kong Island rails"],
    ["PEAK", "Where the funicular goes"],
    ["HARBOUR", "Victoria ___"],
    ["OCTOPUS", "Card that pays for the whole city"],
    ["MONGKOK", "Dense Kowloon shopping district"],
    ["WANCHAI", "District east of Central"],
    ["CENTRAL", "Hong Kong's business district"],
    ["TYPHOON", "Storm that closes the city"],
    ["HANDOVER", "The 1997 event"],
    ["CANTONESE", "Language of Hong Kong"],
    ["SKYLINE", "What the nightly light show lights up"],
    ["FERRY", "Star ___, across the water"],
    ["JADE", "Green stone sold at a Kowloon market"],
    ["CHACHAAN", "Hong Kong diner, informally"],
  ],

  vietnam: [
    ["PHO", "Beef noodle soup for breakfast"],
    ["HANOI", "Vietnam's capital"],
    ["SAIGON", "Ho Chi Minh City, formerly"],
    ["HUE", "Old imperial capital of Vietnam"],
    ["MEKONG", "River with a huge delta"],
    ["HALONG", "Bay of limestone karsts"],
    ["BANHMI", "Baguette sandwich, Vietnamese style"],
    ["DONG", "Money in Hanoi"],
    ["AODAI", "Long tunic over trousers"],
    ["DANANG", "Coastal city with a big beach"],
    ["HOIAN", "Lantern-lit old trading town"],
    ["SAPA", "Terraced hills in the north"],
    ["NUOCMAM", "Vietnamese fish sauce"],
    ["MOPED", "How everyone gets around Hanoi"],
    ["DELTA", "What the Mekong forms"],
    ["PADDY", "Flooded rice field"],
    ["LANTERN", "Paper light strung over Hoi An"],
    ["CONICAL", "Shape of the classic Vietnamese hat"],
  ],

  pcs: [
    ["RAM", "Memory measured in gigabytes"],
    ["CPU", "The chip that does the thinking"],
    ["GPU", "Chip that draws the pixels"],
    ["SSD", "Drive with no moving parts"],
    ["PSU", "Box that feeds the whole build"],
    ["USB", "Port for nearly everything"],
    ["BIOS", "Firmware you hit Delete to reach"],
    ["MOBO", "Board everything plugs into"],
    ["FAN", "Spinning thing that keeps it cool"],
    ["HDMI", "Cable to the monitor"],
    ["CACHE", "Fast memory close to the core"],
    ["TOWER", "Upright PC case"],
    ["HEATSINK", "Finned lump of metal on a chip"],
    ["THERMAL", "___ paste, between chip and cooler"],
    ["OVERCLOCK", "Push it past the rated speed"],
    ["CHIPSET", "What decides which CPU fits"],
    ["FIRMWARE", "Software baked into the hardware"],
    ["MONITOR", "Where the picture ends up"],
    ["KEYBOARD", "Clacky input device"],
    ["REBOOT", "Turn it off and on again"],
    ["SOCKET", "Where the processor drops in"],
    ["LATENCY", "Delay, measured in milliseconds"],
    ["BUILD", "What you spend a weekend on"],
    ["RIG", "Enthusiast's machine"],
    ["BOOT", "Start up"],
    ["DRIVER", "Software that talks to the hardware"],
  ],

  "video gaming": [
    ["NPC", "Character the game controls"],
    ["LOOT", "What drops off the boss"],
    ["BOSS", "Big one at the end of the level"],
    ["NERF", "Patch note that makes it weaker"],
    ["BUFF", "Patch note that makes it stronger"],
    ["RAID", "Group fight for the endgame"],
    ["QUEST", "Task with a reward at the end"],
    ["GRIND", "Repetitive path to a level"],
    ["LAG", "Why you missed the shot"],
    ["SPAWN", "Appear on the map"],
    ["RESPAWN", "Come back after dying"],
    ["SPEEDRUN", "Playthrough against the clock"],
    ["PATCH", "Update that changes the balance"],
    ["COMBO", "String of hits that connect"],
    ["MELEE", "Up-close attack"],
    ["MANA", "Blue bar you spend on spells"],
    ["GUILD", "Players who play together"],
    ["CONSOLE", "Box under the television"],
    ["CONTROLLER", "Thing with two sticks"],
    ["ARCADE", "Where quarters used to go"],
    ["PIXEL", "Smallest piece of the picture"],
    ["SPRITE", "Flat 2D game graphic"],
    ["CHECKPOINT", "Where you restart, mercifully"],
    ["SANDBOX", "Game with no particular goal"],
    ["ROGUELIKE", "Genre where death starts you over"],
    ["EMULATOR", "Software that pretends to be a console"],
    ["INDIE", "Small-studio release"],
    ["COOP", "Playing together against the game"],
    ["SAVE", "What you forgot to do"],
    ["LEVEL", "Both a stage and a number"],
  ],

  "board games": [
    ["MEEPLE", "Little wooden person"],
    ["PAWN", "Smallest chess piece"],
    ["DICE", "Rolled to decide things"],
    ["TILE", "Piece you place, not play"],
    ["DECK", "Stack you draw from"],
    ["ROOK", "Chess piece on the corner"],
    ["BISHOP", "Chess piece stuck on one colour"],
    ["KNIGHT", "Chess piece that jumps"],
    ["CATAN", "Game of settling and trading"],
    ["CHESS", "Sixty-four squares"],
    ["DOMINO", "Tile with two numbers"],
    ["TOKEN", "Marker on the board"],
    ["GAMBIT", "Opening that gives something up"],
    ["STALEMATE", "Nobody wins"],
    ["CHECKERS", "Draughts, in America"],
    ["MONOPOLY", "Game that ends friendships"],
    ["SCRABBLE", "Game of tiles and triple word scores"],
    ["BACKGAMMON", "Ancient game of points and pips"],
    ["SETTLER", "Catan piece before the city"],
    ["TRADE", "Deal made across the table"],
    ["VICTORY", "___ points, the usual win condition"],
    ["WORKER", "___ placement, a game genre"],
    ["ROLL", "What starts most turns"],
    ["TURN", "Yours, then theirs"],
  ],

  boston: [
    ["FENWAY", "Park with the Green Monster"],
    ["CELTICS", "Green banners in the rafters"],
    ["BRUINS", "Boston's hockey team"],
    ["CHOWDER", "Creamy clam soup"],
    ["BEACON", "___ Hill, gaslit and steep"],
    ["CHARLES", "River between Boston and Cambridge"],
    ["HARVARD", "School across the river"],
    ["BACKBAY", "Neighbourhood built on filled land"],
    ["DUCKBOAT", "Amphibious ride, and a parade vehicle"],
    ["SOUTHIE", "South Boston, locally"],
    ["FANEUIL", "___ Hall, market and meeting place"],
    ["COMMON", "America's oldest public park"],
    ["ESPLANADE", "Riverside strip with the Hatch Shell"],
    ["CITGO", "Sign over Kenmore Square"],
    ["MBTA", "The T, formally"],
    ["CANNOLI", "North End dessert"],
    ["NORTHEND", "Boston's Italian quarter"],
    ["SEAPORT", "Boston's newest neighbourhood"],
    ["ALLSTON", "Student-heavy Boston neighbourhood"],
    ["LOBSTER", "___ roll, the summer order"],
    ["WICKED", "New England intensifier"],
    ["BUNKERHILL", "Monument in Charlestown"],
    ["MASSPIKE", "Interstate 90, locally"],
    ["KENMORE", "Square near Fenway"],
    ["SOX", "Boston's nine, briefly"],
  ],

  "arlington ma": [
    ["ARLINGTON", "Town between Cambridge and Lexington"],
    ["SPYPOND", "Arlington's pond, oddly named"],
    ["MENOTOMY", "Arlington's name before 1867"],
    ["MASSAVE", "The long road through Arlington"],
    ["MINUTEMAN", "Bikeway on an old rail bed"],
    ["ROBBINS", "Arlington's library and farm"],
    ["MYSTIC", "Lakes and river north of Arlington"],
    ["HEIGHTS", "Arlington's western end"],
    ["CAPITOL", "Arlington's old movie theatre"],
    ["BIKEWAY", "What the old railway became"],
    ["TOWNDAY", "Arlington's street festival"],
    ["WHITTEMORE", "Arlington park and street name"],
  ],

  "quincy ma": [
    ["QUINCY", "City of Presidents"],
    ["ADAMS", "Two presidents from Quincy"],
    ["GRANITE", "Stone quarried in Quincy"],
    ["WOLLASTON", "Quincy beach and station"],
    ["MERRYMOUNT", "Quincy neighbourhood and park"],
    ["SQUANTUM", "Peninsula in Quincy"],
    ["MARINABAY", "Waterfront development in Quincy"],
    ["HANCOCK", "Quincy's main street"],
    ["SHIPYARD", "Fore River works, historically"],
    ["PRESIDENTS", "What Quincy calls itself the city of"],
    ["NEPONSET", "River between Quincy and Boston"],
  ],

  healthcare: [
    ["NURSE", "Who actually runs the floor"],
    ["TRIAGE", "Sorting by urgency"],
    ["CHART", "Where the visit gets written down"],
    ["VITALS", "Pulse, pressure and the rest"],
    ["INTAKE", "First paperwork of the visit"],
    ["CLINIC", "Outpatient setting"],
    ["WARD", "Hospital unit"],
    ["ROUNDS", "Morning walk past every bed"],
    ["SCRUBS", "Hospital uniform"],
    ["GURNEY", "Wheeled stretcher"],
    ["DOSE", "How much, and how often"],
    ["REFERRAL", "Note that sends you to a specialist"],
    ["COPAY", "What you owe at the desk"],
    ["PREMIUM", "Monthly cost of coverage"],
    ["DEDUCTIBLE", "What you pay before coverage starts"],
    ["PROVIDER", "The one billing for care"],
    ["PAYER", "The one paying the claim"],
    ["DISCHARGE", "Going-home paperwork"],
    ["ADMISSION", "Coming-in paperwork"],
    ["SURGERY", "What the theatre is for"],
    ["PHARMACY", "Where the prescription is filled"],
    ["DIAGNOSIS", "The name for what is wrong"],
    ["SYMPTOM", "What the patient reports"],
    ["XRAY", "Quick look at the bones"],
    ["ICU", "Unit for the sickest patients"],
    ["STAT", "Hospital word for right now"],
  ],

  "big pharma": [
    ["PATENT", "Twenty years of exclusivity"],
    ["GENERIC", "Same molecule, lower price"],
    ["TRIAL", "Phase one, two or three"],
    ["PLACEBO", "The sugar pill arm"],
    ["FDA", "Agency that says yes or no"],
    ["BIOTECH", "Smaller firm that gets acquired"],
    ["PIPELINE", "Everything still in development"],
    ["APPROVAL", "What the submission is chasing"],
    ["REBATE", "Money quietly flowing back to the payer"],
    ["FORMULARY", "List of what the plan will cover"],
    ["BLOCKBUSTER", "Drug earning over a billion"],
    ["EFFICACY", "Whether it actually works"],
    ["MOLECULE", "The active thing in the pill"],
    ["COMPOUND", "Candidate before it has a name"],
    ["LICENSE", "Right to sell someone else's drug"],
    ["INSULIN", "Drug whose pricing became a scandal"],
    ["VACCINE", "Shot that teaches the immune system"],
    ["CLINICAL", "___ trial"],
    ["DOSAGE", "Strength on the label"],
    ["LOBBYING", "How the industry talks to Congress"],
  ],
};
