// Topics introduced for the themed packs, plus extra depth for the topics the
// packs lean on.
//
// Depth is what matters. Measured on this generator: a 5x5 built from ~150
// themed answers comes out about 18% themed, ~300 gets you 21%, ~500 gets you
// 27%. Narrowing to five subjects does not raise the proportion by itself — it
// lowers it, because it shrinks the vocabulary. The only fix is more answers
// per subject.

export const PACK_THEMES = {
  ai: [
    ["PROMPT", "What you type at the model"],
    ["TOKEN", "The unit a model actually reads"],
    ["MODEL", "The trained thing itself"],
    ["NEURAL", "___ network"],
    ["TRAIN", "Show it a few billion examples"],
    ["WEIGHTS", "What training actually changes"],
    ["LAYER", "One stage of the network"],
    ["VECTOR", "Text turned into numbers"],
    ["EMBED", "Turn text into a vector"],
    ["DATASET", "What it learned from"],
    ["CONTEXT", "How much it can hold at once"],
    ["AGENT", "Model given tools and a loop"],
    ["CHATBOT", "The consumer-facing shape of it"],
    ["INFERENCE", "Running the model, not training it"],
    ["FINETUNE", "Nudge a trained model at a task"],
    ["TRANSFORMER", "The architecture behind all of it"],
    ["GPU", "What the training runs on"],
    ["BENCHMARK", "Score it against everyone else"],
    ["OPENSOURCE", "Weights anyone can download"],
    ["LATENCY", "How long before the first word"],
    ["STREAM", "Send the answer as it is written"],
    ["PARAMS", "Counted in billions"],
    ["BIAS", "What the training data smuggled in"],
    ["GUARDRAIL", "What stops it saying that"],
    ["CHAIN", "___ of thought"],
    ["RETRIEVAL", "Look it up before answering"],
    ["SAMPLING", "How the next token gets picked"],
    ["EPOCH", "One pass over the training data"],
    ["BATCH", "Examples processed together"],
    ["DEPLOY", "Get it in front of users"],
  ],

  "cambridge ma": [
    ["CAMBRIDGE", "City across the river from Boston"],
    ["MIT", "School at the Kendall end"],
    ["HARVARDSQ", "Cambridge's best-known square"],
    ["CENTRALSQ", "Between Harvard and Kendall"],
    ["PORTER", "Square with the very long escalator"],
    ["INMAN", "Quieter Cambridge square"],
    ["ALEWIFE", "End of the red line"],
    ["CHARLES", "River Cambridge sits on"],
    ["DOME", "The great one at MIT"],
    ["HACK", "MIT prank, traditionally on the dome"],
    ["BRATTLE", "Cambridge street and cinema"],
    ["MEMDRIVE", "Road along the Cambridge riverbank"],
    ["TECH", "What MIT is short for"],
    ["BIOTECH", "What Kendall Square is now"],
  ],

  "somerville ma": [
    ["SOMERVILLE", "City north of Cambridge"],
    ["DAVISSQ", "Somerville square on the red line"],
    ["UNIONSQ", "Somerville square that got the green line"],
    ["BALLSQ", "Somerville square near Tufts"],
    ["ASSEMBLY", "Somerville's riverside development"],
    ["TUFTS", "University on the Somerville hill"],
    ["WINTERHILL", "Somerville neighbourhood"],
    ["PORCHFEST", "Somerville's music-on-the-stoop day"],
    ["TRIANGLE", "Shape of a Somerville lot, famously"],
  ],

  mbta: [
    ["MBTA", "Who runs the T"],
    ["REDLINE", "Alewife to Braintree"],
    ["GREENLINE", "The one with the trolleys"],
    ["ORANGELINE", "Oak Grove to Forest Hills"],
    ["BLUELINE", "The one under the harbour"],
    ["CHARLIE", "___ Card, how you pay"],
    ["COMMUTER", "___ rail, out to the suburbs"],
    ["TROLLEY", "What runs on the green line"],
    ["PARKST", "Where red meets green"],
    ["BRAINTREE", "Southern end of a red line branch"],
    ["SILVER", "The line that is really a bus"],
    ["FARE", "What the gate wants"],
    ["PLATFORM", "Where you wait"],
    ["SHUTTLE", "Bus replacing the train this weekend"],
    ["DELAY", "The other thing you wait for"],
    ["INBOUND", "Toward downtown"],
    ["OUTBOUND", "Away from downtown"],
    ["TRACK", "What the train runs on"],
  ],

  "beth israel": [
    ["BIDMC", "Beth Israel Deaconess, in initials"],
    ["DEACONESS", "The other half of the name"],
    ["LONGWOOD", "Boston's medical area"],
    ["TEACHING", "___ hospital, one with residents"],
    ["RESIDENT", "Doctor still in training"],
    ["ATTENDING", "The senior doctor on the case"],
    ["INTERN", "First-year resident"],
    ["ROUNDING", "Going bed to bed with the team"],
    ["ONCALL", "Whose pager goes off"],
    ["ADMIT", "Bring a patient in"],
  ],

  // --- extra depth for topics the packs lean on ----------------------------

  "video gaming": [
    ["QUEUE", "Where you wait for a match"],
    ["LOBBY", "Where the team gathers"],
    ["MATCH", "One game against other players"],
    ["RANKED", "Where the stakes are"],
    ["SEASON", "Block of content with a battle pass"],
    ["EMOTE", "Dance you paid for"],
    ["EXPANSION", "The big paid update"],
    ["CAMPAIGN", "The single-player story"],
    ["SIDEQUEST", "The one you do instead"],
    ["INVENTORY", "Where the loot piles up"],
    ["COOLDOWN", "Wait before you can use it again"],
    ["HITBOX", "Where the game thinks you are"],
    ["TUTORIAL", "The bit everyone skips"],
    ["ACHIEVEMENT", "Pop-up for doing something odd"],
    ["STREAMER", "The one playing for an audience"],
    ["ESPORTS", "Competitive play, professionally"],
    ["MODDING", "Changing the game yourself"],
    ["SPEEDRUNNER", "One racing the clock through a game"],
  ],

  memes: [
    ["BANTER", "Friendly winding-up"],
    ["THREAD", "Where the joke got long"],
    ["FORMAT", "The template the joke reuses"],
    ["TEMPLATE", "Blank image awaiting a caption"],
    ["IRONIC", "The layer above sincere"],
    ["NORMIE", "One who arrived late to the joke"],
    ["TOUCHGRASS", "Advice for the terminally online"],
    ["RATIO", "More replies than likes"],
    ["SLAPS", "Praise for a very good track"],
    ["MID", "Damning verdict, in one syllable"],
    ["GYATT", "Recent bit of internet slang"],
    ["SKIBIDI", "Nonsense word from a viral series"],
    ["DELULU", "Cheerfully deluded, online"],
  ],

  reddit: [
    ["CAKEDAY", "Your account's birthday"],
    ["SIDEBAR", "Where the rules live"],
    ["STICKY", "Post pinned to the top"],
    ["AUTOMOD", "Bot that removes your post"],
    ["BRIGADE", "Pile-on from another community"],
    ["SHADOWBAN", "Banned without being told"],
    ["THROWAWAY", "Account made for one confession"],
    ["NOVELTY", "Account with one running joke"],
    ["ARCHIVE", "Where old threads go"],
  ],

  pcs: [
    ["AIRFLOW", "What the case is designed for"],
    ["RADIATOR", "Where liquid cooling dumps the heat"],
    ["SLEEVED", "How the good cables look"],
    ["BENCHMARK", "Score to compare builds"],
    ["THROTTLE", "What heat makes it do"],
    ["BOTTLENECK", "The part holding the rest back"],
    ["FORMFACTOR", "ATX or ITX"],
    ["STANDOFF", "Little screw that lifts the board"],
    ["PASTE", "Goes between chip and cooler"],
    ["CABLEMGMT", "The bit behind the tray"],
  ],

  "graphics cards": [
    ["TENSOR", "Core type for matrix work"],
    ["LAUNCH", "The day nobody can buy one"],
    ["STOCK", "What there is none of at launch"],
    ["OVERHEAD", "What the driver costs you"],
    ["ARTIFACT", "Sign the card is unwell"],
    ["SAGGING", "What a heavy card does in the slot"],
  ],

  japan: [
    ["KONBINI", "Convenience store, in Japan"],
    ["SHINJUKU", "Tokyo's busiest station"],
    ["GINZA", "Tokyo's expensive shopping district"],
    ["AKIHABARA", "Tokyo's electronics quarter"],
    ["OKONOMIYAKI", "Savoury pancake of Osaka"],
    ["TAKOYAKI", "Octopus balls from a street cart"],
    ["MELONPAN", "Sweet bun with a crackly top"],
    ["SUICA", "Tokyo's tap-to-ride card"],
    ["KAISEKI", "Many-course Japanese meal"],
    ["SENTO", "Neighbourhood public bath"],
  ],

  korea: [
    ["HALLYU", "The Korean wave"],
    ["SSAM", "Wrapped in a leaf, Korean style"],
    ["JEON", "Korean savoury pancake"],
    ["HODU", "Walnut, in Korean sweets"],
    ["ITAEWON", "International district of Seoul"],
    ["HONGDAE", "Seoul's student nightlife area"],
    ["PANSORI", "Korean sung storytelling"],
    ["SEOLLAL", "Korean lunar new year"],
  ],

  "hong kong": [
    ["MIDLEVELS", "Where the long escalator climbs"],
    ["SOHO", "Hong Kong's restaurant hillside"],
    ["REPULSE", "___ Bay, on the south side"],
    ["STANLEY", "Market town on Hong Kong Island"],
    ["CHEUNGCHAU", "Island with the bun festival"],
    ["MILKTEA", "Hong Kong's strong, sweet brew"],
  ],

  vietnam: [
    ["NHATRANG", "Vietnamese beach city"],
    ["CANTHO", "City in the Mekong delta"],
    ["BUNCHA", "Hanoi grilled pork and noodles"],
    ["CACHE", "___ phe sua da, iced coffee"],
    ["XICHLO", "Cycle rickshaw of Vietnam"],
  ],

  travel: [
    ["STOPOVER", "Deliberate long layover"],
    ["OPENJAW", "Fly into one city, out of another"],
    ["BACKPACK", "How the cheap trip is carried"],
    ["PHRASEBOOK", "Pocket help with the language"],
    ["ADAPTER", "What you always forget"],
    ["EXCHANGE", "Where the rate is worst"],
    ["EMBASSY", "Where you go when it goes wrong"],
    ["SOUVENIR", "Regretted at customs"],
    ["EXCURSION", "The day trip"],
  ],

  healthcare: [
    ["FORMULARY", "What the plan will pay for"],
    ["PRIORAUTH", "Permission before the treatment"],
    ["INPATIENT", "Staying the night"],
    ["OUTPATIENT", "Home the same day"],
    ["FOLLOWUP", "The next appointment"],
    ["CHARTING", "Writing it all down afterwards"],
    ["HANDOFF", "Passing the patient to the next shift"],
    ["ALLERGY", "Flagged in red on the chart"],
    ["DOSING", "How much and how often"],
    ["INFUSION", "Slow drip of a drug"],
  ],

  "big pharma": [
    ["ROYALTY", "Cut paid to the originator"],
    ["ORPHAN", "___ drug, for a rare disease"],
    ["BIOSIMILAR", "The generic of a biologic"],
    ["ENDPOINT", "What the trial is measuring"],
    ["ENROLMENT", "Getting patients into the trial"],
    ["ADVERSE", "___ event, the bad kind"],
    ["PIPELINE", "Everything not yet approved"],
  ],

  boston: [
    ["EMERSON", "College on the Common"],
    ["COPLEY", "Square with the library and the church"],
    ["PRUDENTIAL", "Boston tower with the view"],
    ["HANOVER", "The North End's main street"],
    ["CHARLESTOWN", "Where the monument is"],
    ["JAMAICAPLAIN", "Boston's JP"],
    ["ROSLINDALE", "Boston neighbourhood south of JP"],
    ["FROGPOND", "Where the Common skates"],
    ["SWANBOAT", "Public Garden ride"],
  ],

  "arlington ma": [
    ["RESERVOIR", "Arlington's swimming water"],
    ["MENOTOMYRIVER", "Waterway through Arlington"],
    ["THEATRE", "The Capitol, on Mass Ave"],
  ],

  golf: [
    ["TEETIME", "What you booked for 7am"],
    ["BACKNINE", "The second half"],
    ["FRONTNINE", "The first half"],
    ["MATCHPLAY", "Hole by hole, not stroke by stroke"],
    ["PROVISIONAL", "Second ball, just in case"],
  ],

  "rock climbing": [
    ["BOULDERING", "Ropeless, over a pad"],
    ["CAMPUS", "___ board, for the very strong"],
    ["HANGBOARD", "Fingers only, at home"],
    ["FLAPPER", "Torn skin on a fingertip"],
    ["BARNDOOR", "Swinging off when the body turns"],
    ["SMEAR", "Trust the rubber, not a hold"],
  ],

  yoga: [
    ["SUNSALUTE", "Opening sequence of a class"],
    ["BOLSTER", "Long supportive cushion"],
    ["RESTORATIVE", "The slow, propped-up class"],
    ["PRANAYAMA", "Breath work"],
    ["DRISHTI", "Where you fix your gaze"],
  ],

  dogs: [
    ["HEEL", "Command to walk alongside"],
    ["STAY", "Command that lasts longest"],
    ["HARNESS", "Alternative to a collar"],
    ["DOGPARK", "Off-lead social hour"],
    ["SHEDDING", "Season on your trousers"],
    ["ADOPTION", "How the rescue ends"],
    ["MICROCHIP", "Under the skin, between the shoulders"],
  ],

  "board games": [
    ["EUROGAME", "Wooden cubes and no dice rolling"],
    ["AMERITRASH", "Dice, minis and betrayal"],
    ["DRAFTING", "Pick one, pass the rest"],
    ["DECKBUILD", "Genre where you make the deck as you play"],
    ["COOPERATIVE", "Everyone against the board"],
    ["ROLLANDMOVE", "The kind your family owns"],
  ],
};

/**
 * Short pack answers, three to five letters. A 5x5 is mostly short entries, so
 * this is where a pack's density is actually won or lost. Words that already
 * exist under another topic reappear here on purpose: the extra topic tag is
 * what lets a pack count them as themed.
 */
export const PACK_SHORT = {
  ai: [
    ["BOT", "Automated account, or an early chatbot"],
    ["LLM", "Large language model, in initials"],
    ["CHAT", "The interface most people meet it through"],
    ["TUNE", "Adjust a trained model"],
    ["SEED", "Number that makes a run repeatable"],
    ["TEMP", "Dial between dull and unhinged"],
    ["MASK", "Hide tokens during training"],
    ["HEAD", "One of the attention ones"],
    ["EVAL", "How you score a model"],
    ["LOSS", "What training drives down"],
    ["RAG", "Retrieval-augmented generation"],
    ["NET", "Neural ___"],
    ["FIT", "What a model does to its data"],
    ["RANK", "Order the results"],
  ],
  "cambridge ma": [
    ["MIT", "School at the Kendall end"],
    ["LAB", "What Cambridge has a lot of"],
    ["SQUARE", "Harvard, Central, Porter or Inman"],
    ["RIVER", "What separates it from Boston"],
  ],
  "somerville ma": [
    ["DAVIS", "Somerville's red line square"],
    ["BALL", "___ Square, near Tufts"],
    ["UNION", "___ Square, Somerville"],
    ["HILL", "Winter ___, in Somerville"],
  ],
  mbta: [
    ["BUS", "The T's other fleet"],
    ["TAP", "How the Charlie Card works"],
    ["STOP", "Where the bus pulls in"],
    ["LINE", "Red, orange, blue or green"],
    ["RAIL", "Commuter ___"],
    ["GATE", "What the fare opens"],
    ["PASS", "Monthly ticket"],
    ["RIDE", "What you are paying for"],
    ["TRAIN", "What runs on the line"],
  ],
  "beth israel": [
    ["BED", "Unit of hospital capacity"],
    ["LAB", "Where the bloods go"],
    ["MRI", "Scanner in the basement"],
    ["SCRUB", "What the surgeon does first"],
    ["SHIFT", "What the handoff ends"],
  ],
  "video gaming": [
    ["WIN", "The good outcome"],
    ["TIER", "S, A or B"],
    ["PING", "Milliseconds to the server"],
    ["ROLE", "Tank, healer or damage"],
    ["MAIN", "The character you always pick"],
    ["ALT", "The character you also play"],
    ["LAN", "Party where everyone brings a tower"],
    ["FARM", "Grind for resources"],
    ["RUSH", "Attack before they are ready"],
  ],
  memes: [
    ["OOF", "Sound of secondhand pain"],
    ["MEH", "Verdict of total indifference"],
    ["STAN", "Devoted fan, as a verb"],
    ["FLOP", "The opposite of viral"],
    ["CAP", "No ___, meaning no lie"],
    ["BRO", "Vocative of the internet"],
  ],
  reddit: [
    ["LURK", "Read without ever posting"],
    ["MOD", "One with the ban hammer"],
    ["SUB", "A community, informally"],
    ["POST", "What gets upvoted"],
    ["EDIT", "Line added after the fact"],
  ],
  pcs: [
    ["HDD", "The drive with moving parts"],
    ["DDR", "What the memory standard is called"],
    ["PORT", "What the cable goes into"],
    ["BOOT", "Start it up"],
    ["CASE", "What it all lives in"],
    ["FAN", "Keeps it cool"],
  ],
  "graphics cards": [
    ["VRAM", "Memory on the card"],
    ["FPS", "Frames per second"],
    ["TDP", "Power the card is rated to draw"],
    ["RTX", "NVIDIA line that sold ray tracing"],
    ["CUDA", "NVIDIA's compute platform"],
  ],
  japan: [
    ["MAKI", "Rolled sushi"],
    ["BAO", "Steamed filled bun"],
    ["SOY", "Sauce on the table"],
    ["RICE", "Under the fish"],
    ["TEA", "Green, and whisked"],
    ["WOK", "Not Japanese, but next door"],
  ],
  korea: [
    ["GIM", "Dried seaweed sheet"],
    ["HAN", "River through Seoul"],
    ["SOJU", "Green bottle on the table"],
    ["KPOP", "Seoul's biggest export"],
    ["JEON", "Korean savoury pancake"],
  ],
  "hong kong": [
    ["MTR", "How you get around Hong Kong"],
    ["BUN", "Pineapple ___"],
    ["PEAK", "Where the funicular goes"],
    ["JUNK", "Red-sailed boat in the harbour"],
    ["TRAM", "Double-decker on rails"],
  ],
  vietnam: [
    ["PHO", "Breakfast noodle soup"],
    ["TET", "Vietnamese new year"],
    ["BUN", "Vietnamese rice noodle"],
    ["HUE", "Old imperial capital"],
    ["BIA", "Beer, in Vietnamese"],
  ],
  travel: [
    ["BAG", "Checked or carried on"],
    ["MAP", "Folded, and never refolded"],
    ["JET", "What you are on"],
    ["CAB", "How you leave the airport"],
    ["INN", "Where you stop for the night"],
    ["SEAT", "27B, say"],
    ["TRIP", "The whole thing"],
  ],
  healthcare: [
    ["ICU", "Where the sickest go"],
    ["ECG", "Trace of the heart"],
    ["DOC", "The one with the stethoscope"],
    ["MED", "What is on the chart"],
    ["PILL", "Taken with water"],
    ["DOSE", "How much"],
    ["SCAN", "CT or MRI"],
    ["VEIN", "Where the needle goes"],
  ],
  "big pharma": [
    ["FDA", "It says yes or no"],
    ["DRUG", "The product"],
    ["TRIAL", "Phase one, two or three"],
    ["LABEL", "What gets approved alongside it"],
    ["PRICE", "The part that makes the news"],
  ],
  boston: [
    ["SOX", "Boston's nine, briefly"],
    ["HUB", "What Boston calls itself"],
    ["PIKE", "The Mass ___"],
    ["BEAN", "___ town"],
    ["POND", "Frog ___, on the Common"],
    ["BAY", "Back ___"],
  ],
  golf: [
    ["TEE", "Where the hole starts"],
    ["PAR", "What the card expects"],
    ["PIN", "The flagstick"],
    ["PUTT", "Stroke on the green"],
    ["LIE", "How the ball is sitting"],
  ],
  "rock climbing": [
    ["JUG", "Hold you can wrap a hand round"],
    ["CAM", "Spring-loaded protection"],
    ["BETA", "Someone else's solution"],
    ["SEND", "Climb it clean at last"],
    ["CRUX", "The hardest move"],
  ],
  yoga: [
    ["MAT", "What you unroll"],
    ["POSE", "One shape in the sequence"],
    ["FLOW", "Sequence of poses"],
    ["TREE", "Balancing pose"],
  ],
  dogs: [
    ["PUP", "Young one"],
    ["PAW", "Shake it"],
    ["WAG", "What the tail does"],
    ["WALK", "The best word there is"],
    ["SIT", "First command taught"],
    ["TOY", "Squeaky thing"],
  ],
  "board games": [
    ["DICE", "Rolled to decide"],
    ["PAWN", "Smallest chess piece"],
    ["TILE", "Placed, not played"],
    ["DECK", "What you draw from"],
    ["ROOK", "Corner chess piece"],
    ["TURN", "Yours, then theirs"],
  ],
};

/**
 * Second pass of depth for the two thinnest packs. Medicine and Greater Boston
 * both came in around 150 answers, which measures out near 18% themed on a 5x5;
 * the rest sit above 220.
 */
export const PACK_EXTRA = {
  healthcare: [
    ["GAUZE", "What the dressing is made of"],
    ["SUTURE", "Closes the wound"],
    ["STENT", "Props a vessel open"],
    ["GRAFT", "Tissue moved from elsewhere"],
    ["BIOPSY", "Take a piece and look at it"],
    ["SEPSIS", "Infection gone body-wide"],
    ["CANNULA", "Tube into the vein"],
    ["THEATRE", "Where the operating happens"],
    ["RECOVERY", "The room after theatre"],
    ["OBS", "Observations, on the chart"],
    ["TEMP", "One of the vital signs"],
    ["BLOODS", "What gets sent to the lab"],
    ["SLING", "Holds the arm still"],
    ["CAST", "Holds the bone still"],
    ["CRUTCH", "Takes the weight off"],
    ["WARDROUND", "Morning walk past every bed"],
    ["BLEEP", "What summons the doctor"],
    ["CONSENT", "Signed before the procedure"],
    ["REFERRAL", "Sends you to the specialist"],
    ["DISCHARGE", "Papers that let you go"],
  ],
  "big pharma": [
    ["ASSAY", "Test of how much is there"],
    ["POTENCY", "How strong the dose is"],
    ["TABLET", "Pressed, not capsuled"],
    ["CAPSULE", "The other shape"],
    ["BATCH", "What gets recalled"],
    ["RECALL", "When the batch goes wrong"],
    ["PATENT", "Twenty years of it"],
    ["CLIFF", "Patent ___, when generics arrive"],
    ["LICENCE", "Right to sell someone else's drug"],
    ["MARKUP", "What the middle adds"],
  ],
  "pharma companies": [
    ["MERCK", "Rahway drugmaker"],
    ["AMGEN", "Thousand Oaks biotech"],
    ["ROCHE", "Basel drugmaker"],
    ["LILLY", "Indianapolis drugmaker"],
    ["BAYER", "It gave us aspirin"],
    ["PFIZER", "New York drugmaker"],
    ["BIOGEN", "Cambridge neurology firm"],
    ["VERTEX", "Boston, and cystic fibrosis"],
  ],
  alnylam: [
    ["RNA", "The molecule it works on"],
    ["GENE", "What gets silenced"],
    ["DOSE", "Given by injection"],
    ["SIRNA", "Small interfering RNA"],
    ["KENDALL", "The square it sits by"],
  ],
  "beth israel": [
    ["WARD", "Where the beds are"],
    ["NURSE", "Who runs the floor"],
    ["CHART", "Where the visit is written"],
    ["PAGER", "Still how the hospital calls you"],
    ["ROTA", "Who is working when"],
    ["CLINIC", "Outpatient session"],
    ["THEATRE", "Where the surgery is"],
  ],
  boston: [
    ["DOT", "Dorchester, locally"],
    ["WHARF", "Long ___, on the waterfront"],
    ["QUINCYMKT", "Market by Faneuil Hall"],
    ["CHOWDA", "How the soup is said here"],
    ["DUCK", "___ boat, and a parade"],
    ["SWAN", "___ boat, in the Public Garden"],
    ["COMMON", "America's oldest public park"],
    ["GARDEN", "Public ___, or where the Celtics play"],
    ["NORTHEND", "The Italian quarter"],
    ["SEAPORT", "The newest neighbourhood"],
    ["HARBOR", "Where the tea went"],
    ["BRUINS", "The hockey team"],
    ["CELTICS", "The basketball team"],
    ["FENWAY", "The oldest park"],
    ["MONSTER", "Green ___, in left field"],
    ["BALLPARK", "What Fenway is"],
    ["MARATHON", "Third Monday in April"],
    ["PATRIOTS", "___ Day, and the football team"],
  ],
  mbta: [
    ["CAR", "One unit of the train"],
    ["ZONE", "How commuter rail is priced"],
    ["MAP", "Coloured lines on the wall"],
    ["TOKEN", "How you used to pay"],
    ["TURNSTILE", "What the card opens"],
    ["ESCALATOR", "Often out of service"],
    ["ANNOUNCE", "What you cannot quite hear"],
    ["TERMINUS", "End of the line"],
  ],
  "cambridge ma": [
    ["ROW", "What the crews do on the Charles"],
    ["HARVARD", "The old school by the square"],
    ["KENDALL", "Square full of biotech"],
    ["SQUARE", "How Cambridge names its centres"],
    ["BRIDGE", "How you get to Boston"],
  ],
  "somerville ma": [
    ["TUFTS", "University on the hill"],
    ["SLUMBREW", "Somerville brewery, familiarly"],
    ["SQUARE", "Davis, Union or Ball"],
  ],
  "arlington ma": [
    ["BIKE", "What the old rail bed carries now"],
    ["TRAIL", "The Minuteman one"],
    ["AVE", "Mass ___, through the middle"],
    ["POND", "Spy ___"],
  ],
  "quincy ma": [
    ["SHORE", "The south one"],
    ["BEACH", "Wollaston's"],
    ["ADAMS", "Two presidents of the name"],
    ["ROCK", "Granite, quarried here"],
  ],
};

/**
 * Third pass, for Medicine and Greater Boston. Both first generated at 14%
 * themed off ~175 answers, against 29% for the pack with 329. Depth is the only
 * lever, and short answers are the ones that matter in a 5x5.
 */
export const PACK_DEPTH = {
  "greek myth": [
    ["GOD", "One of the twelve on the mountain"],
    ["FATE", "What even the gods bow to"],
    ["MYTH", "The story itself"],
    ["EPIC", "Long poem about a hero"],
    ["ODE", "Poem sung to a god"],
    ["URN", "Painted pot the scene is on"],
    ["OWL", "Bird sitting with Athena"],
    ["BOLT", "What the sky god throws"],
    ["ORB", "Apple of discord, roughly"],
    ["SEA", "Poseidon's whole domain"],
    ["SUN", "What Helios drives across"],
    ["MOON", "What Selene drives across"],
    ["FLEECE", "What Jason sailed for"],
    ["ARROW", "What Eros fires"],
    ["SHADE", "The dead, in the underworld"],
    ["COIN", "Fare the ferryman wants"],
    ["OLIVE", "Athena's gift to her city"],
    ["TEMPLE", "Where the offering goes"],
    ["ALTAR", "Where it is burned"],
    ["QUEST", "What the hero is sent on"],
    ["CURSE", "What the god lays on you"],
    ["ROCK", "Sisyphus's daily problem"],
    ["MAZE", "What Daedalus built"],
    ["WINGS", "What melted"],
    ["HORSE", "What the Greeks left outside"],
    ["SNAKE", "What grows from the gorgon's head"],
    ["STONE", "What her look turns you to"],
    ["GIANT", "What the one-eyed one is"],
    ["THREAD", "What got Theseus back out"],
  ],
  pokemon: [
    ["CUTE", "How the mascot is drawn"],
    ["TAIL", "The mascot's is a lightning bolt"],
    ["BOLT", "Shape of that tail"],
    ["EGG", "What hatches after enough steps"],
    ["NEST", "Where the eggs are found"],
    ["ITEM", "What the bag is full of"],
    ["BAG", "Where the balls are kept"],
    ["HEAL", "What the centre does, free"],
    ["POTION", "Twenty hit points back"],
    ["REVIVE", "Item for a fainted one"],
    ["TRADE", "How you get the other version's exclusive"],
    ["WILD", "Kind of encounter in the grass"],
    ["GRASS", "Where the wild ones hide"],
    ["CAVE", "Where the rock types live"],
    ["ROUTE", "Numbered path between towns"],
    ["TOWN", "Where the next gym is"],
    ["RIVAL", "The one who picks the type that beats yours"],
    ["FAINT", "What happens at zero"],
    ["SUPER", "___ effective, for double damage"],
    ["MOVE", "One of four a creature knows"],
    ["STAB", "Same-type attack bonus, in short"],
    ["EXP", "What the share hands round"],
    ["NIDO", "___ran, the one with two forms"],
    ["FIRE", "Starter type with the lit tail"],
    ["ROCK", "Brock's whole gym"],
    ["FLY", "Move that also gets you home"],
    ["SURF", "Move for crossing water"],
    ["DIG", "Move that also gets you out of a cave"],
  ],
  "hades (game)": [
    ["EXIT", "What the whole run is looking for"],
    ["DOOR", "What the symbol above it promises"],
    ["OBOL", "Coin spent in the shop"],
    ["FATE", "What the list keeps track of"],
    ["GIFT", "What nectar counts as"],
    ["POM", "___ of power, one more level"],
    ["FURY", "What Megaera is one of"],
    ["LAVA", "What Asphodel is full of"],
    ["SHOP", "Charon's little stall"],
    ["WELL", "___ of charon, mid-run purchase"],
    ["HOUSE", "Where every run starts"],
    ["SWORD", "The starting one of the six"],
    ["SPEAR", "The long one of the six"],
    ["SHIELD", "The one you can throw"],
    ["FISTS", "The pair of the six"],
    ["RAIL", "The gun of the six"],
    ["BOW", "The ranged one of the six"],
    ["NECTAR", "What buys a keepsake"],
    ["ESCAPE", "The whole point of it"],
    ["FATHER", "Who is sitting at the desk"],
  ],
  healthcare: [
    ["ACHE", "Dull, ongoing pain"],
    ["PAIN", "What the scale is out of ten for"],
    ["RASH", "Reason to see someone about your skin"],
    ["COUGH", "Reason to stay home"],
    ["FEVER", "Over a hundred"],
    ["PULSE", "Beats a minute"],
    ["BLOOD", "What gets taken and sent"],
    ["BONES", "What the X-ray shows"],
    ["HEART", "What the ECG traces"],
    ["LUNGS", "What the stethoscope listens to"],
    ["LIVER", "The body's filter"],
    ["NERVE", "Carries the signal"],
    ["SPINE", "Column of vertebrae"],
    ["JOINT", "Knee or elbow"],
    ["ULCER", "Sore that will not close"],
    ["VIRUS", "What the antibiotic will not touch"],
    ["TOXIN", "What the liver clears"],
    ["GOWN", "What you are given to wear"],
    ["TUBE", "Goes in, one way or another"],
    ["DRIP", "Slow line into the arm"],
    ["PUMP", "Controls the drip"],
    ["CURE", "The hoped-for ending"],
    ["HEAL", "What time does"],
    ["REST", "Half of most advice"],
    ["DIET", "The other half"],
    ["SICK", "Why you came"],
    ["WELL", "Why you left"],
    ["MEDS", "What you go home with"],
    ["LABS", "Results still pending"],
    ["BEDS", "What the hospital counts"],
    ["SHOT", "Given in the arm"],
    ["XRAY", "Quick look at the bones"],
    ["EKG", "Heart trace, spelled the other way"],
    ["HIP", "Commonly replaced joint"],
    ["RIB", "One of twenty-four"],
    ["JAW", "Where the wisdom teeth are"],
    ["GUT", "Where most of it goes wrong"],
    ["FLU", "Winter's reason to call in"],
    ["ARM", "Where the cuff goes"],
    ["EYE", "What the chart tests"],
    ["EAR", "Where the otoscope goes"],
  ],
  "hospital data": [
    ["CODE", "What the visit becomes for billing"],
    ["CLAIM", "Sent to the payer"],
    ["DENIAL", "Sent back by the payer"],
    ["FEED", "Interface between two systems"],
    ["FIELD", "One column in the record"],
    ["QUERY", "How you ask the warehouse"],
    ["TABLE", "Where the rows live"],
    ["EXPORT", "Pull it out for analysis"],
    ["METRIC", "What the dashboard shows"],
    ["AUDIT", "Who looked at which record"],
  ],
  "big pharma": [
    ["PHASE", "One, two or three"],
    ["ARM", "One group in a trial"],
    ["COHORT", "The group being followed"],
    ["DOSE", "How much, how often"],
    ["MGS", "Milligrams, on the label"],
    ["ORAL", "By mouth"],
    ["INJECT", "The other route"],
    ["PATIENT", "Who the trial is for"],
  ],
  "pharma companies": [
    ["MODERNA", "Cambridge mRNA firm"],
    ["GILEAD", "Antiviral specialist"],
    ["ABBVIE", "Spun out of Abbott"],
    ["SANOFI", "French drugmaker"],
    ["TAKEDA", "Japan's largest"],
    ["NOVARTIS", "The other Basel giant"],
  ],
  "beth israel": [
    ["BED", "What the ward counts"],
    ["ROTA", "Who is on when"],
    ["SHIFT", "Twelve hours of it"],
    ["BLEEP", "How you are summoned"],
    ["HANDOVER", "Passing the list on"],
    ["LIST", "Who to see today"],
    ["TEAM", "The consultant's firm"],
    ["ROUND", "Bed to bed"],
  ],
  boston: [
    ["DOCK", "Where the boats tie up"],
    ["WHARF", "Long ___"],
    ["PARK", "Where the Sox play, or the Common"],
    ["HALL", "Faneuil ___"],
    ["SNOW", "What February brings"],
    ["COLD", "What the wind off the harbour is"],
    ["CITY", "What Boston is, of Champions"],
    ["EAST", "___ Boston, by the airport"],
    ["WEST", "___ End, mostly gone"],
    ["NORTH", "___ End, still there"],
    ["SOUTH", "___ Station"],
    ["TEA", "Thrown in 1773"],
    ["AVE", "Comm ___"],
    ["MASS", "___ Ave, the long one"],
    ["GREEN", "Colour of a line and a monster"],
    ["ORANGE", "Another line's colour"],
    ["PLAZA", "City Hall ___"],
    ["ROXBURY", "Boston neighbourhood"],
    ["DORCHESTER", "The Dot, in full"],
    ["BRIGHTON", "Boston's western neighbourhood"],
  ],
  mbta: [
    ["TRACK", "What the train runs on"],
    ["PLATFORM", "Where you stand"],
    ["SIGNAL", "What causes the delay"],
    ["DRIVER", "At the front of the train"],
    ["ROUTE", "The bus's number"],
    ["TIMETABLE", "What the train is not keeping to"],
    ["CROWD", "Rush hour, in a word"],
    ["SEAT", "Hard to get at 8am"],
  ],
  "cambridge ma": [
    ["ROWERS", "On the Charles at dawn"],
    ["YARD", "Harvard's green middle"],
    ["STATA", "MIT's oddly shaped building"],
    ["SQUARES", "How Cambridge is organised"],
  ],
  "somerville ma": [
    ["HILLS", "What Somerville has seven of"],
    ["PORCH", "___ fest, the music day"],
    ["GREENLINE", "It finally reached Union Square"],
  ],
  "arlington ma": [
    ["SPY", "___ Pond"],
    ["TOWN", "Not a city, officially"],
    ["HEIGHTS", "Arlington's western end"],
  ],
  "quincy ma": [
    ["BEACH", "Wollaston's"],
    ["SHORE", "The south one"],
    ["MARINA", "___ Bay"],
    ["PRESIDENT", "Quincy is the city of them"],
  ],
  "worcester ma": [
    ["HEART", "Of the Commonwealth"],
    ["PIES", "Table Talk's little ones"],
    ["CANAL", "___ District"],
  ],
  "leominster ma": [
    ["APPLE", "Johnny ___seed's first name here"],
    ["PLASTIC", "What the city was built on"],
  ],
};

/**
 * Short Boston-area answers. Greater Boston had 217 themed answers but only 86
 * of them three to five letters, because the subject is full of long place
 * names — Dorchester, Somerville, Charlestown — that a 5x5 cannot hold. Density
 * tracks the short count, not the total, so this is the fix.
 */
export const PACK_BOSTON_SHORT = {
  boston: [
    ["LOGAN", "Boston's airport"],
    ["SALEM", "Witch-trial town north of Boston"],
    ["LYNN", "City on the North Shore"],
    ["HULL", "Town at the end of the peninsula"],
    ["ESSEX", "Street in Chinatown, and a county"],
    ["TOBIN", "Bridge to Chelsea"],
    ["ZAKIM", "Cable-stayed bridge over the Charles"],
    ["CLAM", "What the chowder is made of"],
    ["COD", "Cape ___"],
    ["ROLL", "Lobster ___"],
    ["DUNKS", "Where the coffee comes from, locally"],
    ["TONIC", "New England word for soda"],
    ["FRAPPE", "Milkshake, in Massachusetts"],
    ["PACKIE", "Liquor store, locally"],
    ["STATE", "___ Street, downtown"],
    ["ANDREW", "Red line stop in South Boston"],
    ["SAVIN", "___ Hill, on the red line"],
    ["FIELDS", "___ Corner, in Dorchester"],
    ["BACK", "___ Bay"],
    ["FORT", "___ Point, by the channel"],
    ["YARD", "Harvard's green middle"],
    ["ROW", "What the crews do on the Charles"],
    ["BAY", "Back ___, or the harbour"],
    ["AVE", "Comm ___"],
  ],
  mbta: [
    ["ALEWIFE", "Northern end of the red line"],
    ["KENMORE", "Stop by Fenway"],
    ["COPLEY", "Green line stop by the library"],
    ["PORTER", "Stop with the very long escalator"],
    ["INMAN", "Cambridge square without a station"],
    ["STATE", "Where blue meets orange"],
    ["NORTH", "___ Station"],
    ["SOUTH", "The other big station"],
    ["PARK", "___ Street, where red meets green"],
    ["GREEN", "The trolley line"],
    ["BLUE", "The line under the harbour"],
    ["RED", "Alewife to Braintree"],
    ["BUS", "The other fleet"],
    ["CARD", "Charlie ___"],
    ["TAP", "How you pay now"],
    ["STOP", "Where the bus pulls in"],
    ["FARE", "What the gate wants"],
    ["LATE", "What the train is"],
  ],
  "cambridge ma": [
    ["MIT", "At the Kendall end"],
    ["YARD", "Harvard's"],
    ["LAB", "What the city is full of"],
    ["ROW", "Crews on the Charles"],
    ["STATA", "MIT's oddly shaped building"],
    ["INMAN", "Quieter Cambridge square"],
  ],
  "somerville ma": [
    ["DAVIS", "The red line square"],
    ["BALL", "___ Square"],
    ["UNION", "___ Square"],
    ["HILL", "Winter ___"],
    ["TUFTS", "The university on the hill"],
    ["PORCH", "___ fest"],
  ],
  "arlington ma": [
    ["SPY", "___ Pond"],
    ["POND", "Spy ___"],
    ["AVE", "Mass ___"],
    ["BIKE", "What the old rail bed carries"],
    ["TOWN", "Not a city, officially"],
  ],
  "quincy ma": [
    ["ADAMS", "Two presidents"],
    ["BEACH", "Wollaston's"],
    ["SHORE", "The south one"],
    ["ROCK", "Granite, quarried here"],
    ["BAY", "Marina ___"],
  ],
  "worcester ma": [
    ["WOO", "Worcester, in a nickname"],
    ["PIE", "Table Talk's"],
    ["HILL", "What Holy Cross sits on"],
    ["CANAL", "___ District"],
    ["CLARK", "University in Worcester"],
  ],
  "leominster ma": [
    ["APPLE", "Johnny ___seed's fruit"],
    ["FARM", "Sholan ___"],
    ["ROUTE", "___ 2, north of town"],
  ],
};
