// Extra themed answers that only appear in Clem's puzzles.
export const CLEM_THEMES = {
  programming: [
    ["LOOP", "Block that runs until it shouldn't"],
    ["ARRAY", "Indexed list"],
    ["CLASS", "Blueprint for an object"],
    ["DEBUG", "Hunt the thing you wrote yesterday"],
    ["COMPILE", "Turn source into something runnable"],
    ["STACK", "Where the call frames go"],
    ["HEAP", "Where the allocations go"],
    ["REGEX", "Pattern nobody can read a week later"],
    ["API", "How one program asks another for things"],
    ["GIT", "Version control everyone uses"],
    ["MERGE", "Bring two branches together"],
    ["COMMIT", "Save a change to history"],
    ["REBASE", "Replay commits on a new base"],
    ["BRANCH", "Line of development"],
    ["LINT", "Tool that nags about style"],
    ["REFACTOR", "Change the shape, not the behaviour"],
    ["RECURSION", "See: recursion"],
    ["POINTER", "Address, not the thing itself"],
    ["BOOLEAN", "True or false"],
    ["STRING", "Text, to a program"],
    ["INTEGER", "Whole number type"],
    ["FUNCTION", "Named block you can call"],
    ["VARIABLE", "Named box for a value"],
    ["EXCEPTION", "Thrown when things go wrong"],
    ["CACHE", "Fast answer you saved earlier"],
    ["THREAD", "One line of execution"],
    ["DEADLOCK", "Two threads waiting on each other forever"],
    ["BUG", "Why it doesn't work"],
    ["PARSE", "Read structure out of text"],
    ["ENUM", "Fixed set of named values"],
  ],

  finance: [
    ["BOND", "Loan you can trade"],
    ["YIELD", "What the bond pays you"],
    ["HEDGE", "Position that offsets another"],
    ["ASSET", "Left side of the balance sheet"],
    ["EQUITY", "Ownership stake"],
    ["MARGIN", "Borrowed money in a brokerage account"],
    ["LEDGER", "Book of record"],
    ["AUDIT", "Someone checking your numbers"],
    ["ACCRUAL", "Recognise it before the cash moves"],
    ["DIVIDEND", "Payout to shareholders"],
    ["PORTFOLIO", "Everything you hold"],
    ["LIQUIDITY", "How easily you can sell"],
    ["ARBITRAGE", "Free money, briefly"],
    ["INTEREST", "The cost of borrowing"],
    ["REVENUE", "Top line"],
    ["EBITDA", "Earnings before the awkward parts"],
    ["INVOICE", "Bill sent to a customer"],
    ["FORECAST", "Numbers you will be wrong about"],
    ["VARIANCE", "Gap between plan and actual"],
  ],

  sql: [
    ["JOIN", "Combine rows from two tables"],
    ["SELECT", "Statement that reads"],
    ["INDEX", "Structure that makes lookups fast"],
    ["QUERY", "What you send to the database"],
    ["TABLE", "Rows and columns"],
    ["SCHEMA", "Shape of the database"],
    ["INNER", "The default kind of join"],
    ["WHERE", "Clause that filters"],
    ["NULL", "Not zero, not empty: unknown"],
    ["PRIMARY", "___ key, unique per row"],
    ["FOREIGN", "___ key, pointing at another table"],
    ["GROUPBY", "Clause that collapses rows"],
    ["HAVING", "Filter applied after grouping"],
    ["ROLLBACK", "Undo the transaction"],
    ["COMMIT", "Make the transaction stick"],
    ["CURSOR", "Row-at-a-time, and usually a mistake"],
    ["UPSERT", "Insert or update, whichever applies"],
    ["DISTINCT", "Keyword that removes duplicates"],
    ["AGGREGATE", "SUM, COUNT and friends"],
    ["DEADLOCKS", "What two transactions do to each other, in the plural"],
  ],

  csharp: [
    ["LINQ", "Query syntax built into C#"],
    ["NUGET", "Where C# packages come from"],
    ["DOTNET", "The runtime, and the CLI"],
    ["ASYNC", "Keyword before a Task-returning method"],
    ["AWAIT", "What you do to a Task"],
    ["NAMESPACE", "How C# organises type names"],
    ["INTERFACE", "Contract without an implementation"],
    ["DELEGATE", "Type that holds a method"],
    ["GENERIC", "Type parameterised by another type"],
    ["NULLABLE", "Reference type that admits it might be nothing"],
    ["STRUCT", "Value type"],
    ["RECORD", "C# type built for immutability"],
  ],

  "magic the gathering": [
    ["MANA", "What you tap lands for"],
    ["TAP", "Turn the card sideways"],
    ["LAND", "Card that makes the mana"],
    ["DRAFT", "Format where you pass the pack"],
    ["FOIL", "Shiny version of a card"],
    ["COMMANDER", "Format built around one legend"],
    ["SIDEBOARD", "Fifteen cards for game two"],
    ["PLANESWALKER", "Card type with loyalty counters"],
    ["MULLIGAN", "Shuffle back and draw one fewer"],
    ["UPKEEP", "Step right after untap"],
    ["COUNTERSPELL", "Blue's answer to everything"],
    ["CREATURE", "The card type that attacks"],
    ["SORCERY", "Spell you can only cast on your turn"],
    ["INSTANT", "Spell you can cast any time"],
    ["ENCHANT", "Stick it to a permanent"],
    ["GRAVEYARD", "Where cards go when they die"],
  ],

  "graphics cards": [
    ["NVIDIA", "Green team"],
    ["RADEON", "AMD's graphics line"],
    ["VRAM", "Memory on the card itself"],
    ["CUDA", "NVIDIA's compute platform"],
    ["RTX", "NVIDIA line that made ray tracing a selling point"],
    ["RAYTRACING", "Lighting technique that costs frames"],
    ["SHADER", "Small program that runs per pixel"],
    ["FRAMERATE", "Measured in FPS"],
    ["UPSCALING", "Render small, display big"],
    ["SCALPER", "Why the card cost double in 2021"],
    ["COOLER", "Fans and fins on the card"],
    ["PCIE", "Slot the card goes in"],
    ["RISER", "Cable that stands the card upright"],
    ["UNDERVOLT", "Less power, nearly the same speed"],
  ],

  dota: [
    ["CREEP", "Lane minion"],
    ["WARD", "Vision on a timer"],
    ["ROSHAN", "Pit boss with the good drop"],
    ["ANCIENT", "Structure you have to destroy"],
    ["MIDLANE", "Where the solo goes"],
    ["TOWER", "Defence that shoots back"],
    ["CARRY", "Farms early, wins late"],
    ["SUPPORT", "Buys the wards"],
    ["DENY", "Kill your own creep"],
    ["COURIER", "Little thing that brings your items"],
    ["JUNGLE", "Between the lanes"],
    ["GANK", "Surprise visit to another lane"],
  ],

  starcraft: [
    ["ZERG", "The swarm"],
    ["PROTOSS", "The psionic race"],
    ["TERRAN", "The human race"],
    ["ZERGLING", "Cheap, fast and never alone"],
    ["MARINE", "Terran's basic infantry"],
    ["RUSH", "Attack before they are ready"],
    ["MACRO", "Keeping the economy going"],
    ["MICRO", "Managing units one by one"],
    ["PYLON", "You must construct additional ones"],
    ["OVERLORD", "Zerg unit that provides supply"],
    ["MINERALS", "Blue resource"],
    ["EXPAND", "Take a second base"],
  ],

  "elden ring": [
    ["TARNISHED", "You, in the Lands Between"],
    ["RUNES", "Currency you drop when you die"],
    ["GRACE", "Site you rest at"],
    ["ERDTREE", "Glowing thing on the horizon"],
    ["MALENIA", "Blade of Miquella"],
    ["LIMGRAVE", "Where everyone starts"],
    ["MARGIT", "First real wall"],
    ["ASHES", "Spirit summons"],
    ["FLASK", "What you sip before the boss"],
    ["INVADER", "Uninvited player"],
    ["POISE", "Stat that decides who flinches"],
    ["ELDENRING", "The thing the title refers to"],
  ],

  "red dead redemption": [
    ["ARTHUR", "Morgan of the Van der Linde gang"],
    ["DUTCH", "He has a plan"],
    ["LASSO", "Rope for catching a horse"],
    ["SALOON", "Where the piano is"],
    ["POSSE", "Riding group"],
    ["VALENTINE", "Muddy cattle town"],
    ["BOUNTY", "Price on your head"],
    ["STAGECOACH", "Robbery target"],
    ["PELT", "What the hunter sells"],
    ["CAMP", "Where the gang keeps its things"],
    ["HONOR", "Meter that tracks your choices"],
    ["OUTLAW", "What you are, essentially"],
  ],

  "sysadmin and helpdesk": [
    ["TICKET", "Where every request begins"],
    ["REBOOT", "First thing to try"],
    ["DOMAIN", "What the workstation joins"],
    ["SERVER", "The machine in the rack"],
    ["BACKUP", "Untested until you need it"],
    ["VPN", "Tunnel into the network"],
    ["DNS", "It is always this"],
    ["PING", "Simple reachability check"],
    ["ADMIN", "Account with the good permissions"],
    ["PATCH", "Tuesday's chore"],
    ["UPTIME", "How long since the last reboot"],
    ["SUBNET", "Slice of an address range"],
    ["FIREWALL", "What is blocking the port"],
    ["ONCALL", "Whose phone rings at 3am"],
    ["OUTAGE", "Why the phone is ringing"],
    ["ESCALATE", "Send it up a tier"],
    ["IMAGING", "Putting a fresh build on a laptop"],
    ["PASSWORD", "Most common reset request"],
    ["LOGFILE", "Where the answer usually is"],
  ],

  "hospital data": [
    ["HLSEVEN", "Old messaging standard for health data"],
    ["FHIR", "Modern health data exchange standard"],
    ["CLAIM", "What gets sent to the payer"],
    ["ENCOUNTER", "One visit, in the data model"],
    ["CODING", "Turning a visit into billable codes"],
    ["DENIAL", "Claim the payer sent back"],
    ["REGISTRY", "Curated list of patients with a condition"],
    ["COHORT", "Group defined by shared criteria"],
    ["EXTRACT", "Pull from the source system"],
    ["MAPPING", "Getting one system's codes to mean another's"],
    ["DASHBOARD", "Where the metrics land"],
    ["INTERFACE", "The feed between two systems"],
    ["DOWNTIME", "When the EHR is unavailable"],
    ["AUDITLOG", "Who looked at which record"],
  ],
};
