// Extra themed answers that only appear in Lori's puzzles.
export const LORI_THEMES = {
  instagram: [
    ["REEL", "Short vertical video"],
    ["STORY", "Post that disappears after a day"],
    ["FEED", "What you scroll"],
    ["FILTER", "What makes the photo look like that"],
    ["FOLLOW", "Start seeing someone's posts"],
    ["HASHTAG", "Word after the pound sign"],
    ["CAPTION", "Words under the picture"],
    ["SELFIE", "Photo of the photographer"],
    ["HANDLE", "The name after the at sign"],
    ["CAROUSEL", "Post you swipe through"],
    ["EXPLORE", "Tab full of things you never asked for"],
    ["INFLUENCER", "One paid to hold the product"],
    ["BOOMERANG", "Clip that plays forwards then back"],
    ["VERIFIED", "What the blue tick means"],
    ["GRID", "How a profile lays out its photos"],
    ["TAG", "Attach a friend to a photo"],
    ["LIKE", "Double-tap result"],
  ],
  travel: [
    ["VISA", "Stamp you may need in advance"],
    ["PASSPORT", "Little book with the stamps"],
    ["LAYOVER", "Time between flights"],
    ["JETLAG", "Why you are awake at 4am"],
    ["HOSTEL", "Cheap bed with strangers"],
    ["ITINERARY", "Day-by-day plan"],
    ["CARRYON", "Bag that goes overhead"],
    ["BOARDING", "___ pass"],
    ["CUSTOMS", "Where they ask what you are bringing in"],
    ["TERMINAL", "Building with the gates"],
    ["REDEYE", "Overnight flight"],
    ["UPGRADE", "Move up the cabin"],
    ["LOUNGE", "Quiet room with free coffee"],
    ["SUITCASE", "What the wheels are attached to"],
    ["AISLE", "Seat you pick to get up easily"],
    ["TRANSIT", "Passing through without entering"],
    ["DUTYFREE", "Airport shop with no tax"],
    ["ROAMING", "What costs a fortune abroad"],
    ["GATE", "Where boarding happens"],
  ],
  "pharma companies": [
    ["PFIZER", "New York drugmaker"],
    ["MERCK", "Drugmaker of Rahway, New Jersey"],
    ["MODERNA", "Cambridge biotech known for mRNA"],
    ["AMGEN", "Thousand Oaks biotech"],
    ["BIOGEN", "Cambridge firm focused on neurology"],
    ["NOVARTIS", "Basel drugmaker"],
    ["ROCHE", "The other Basel drugmaker"],
    ["SANOFI", "French pharmaceutical giant"],
    ["LILLY", "Indianapolis drugmaker"],
    ["ABBVIE", "Spun out of Abbott in 2013"],
    ["BAYER", "German firm that gave us aspirin"],
    ["GILEAD", "Foster City antiviral specialist"],
    ["VERTEX", "Boston firm known for cystic fibrosis drugs"],
    ["TAKEDA", "Japan's largest drugmaker"],
  ],
  alnylam: [
    ["ALNYLAM", "Cambridge company built on RNA interference"],
    ["RNAI", "The interference Alnylam is named for"],
    ["SIRNA", "Small interfering RNA"],
    ["SILENCE", "What RNA interference does to a gene"],
    ["KENDALL", "Cambridge square full of biotech"],
    ["AMYLOID", "Protein that misfolds and builds up"],
    ["THERAPY", "What the treatment is called"],
    ["GENE", "What gets silenced"],
  ],
  genesis: [
    ["GENESIS", "Hyundai's luxury brand, or the first book"],
    ["EDEN", "The garden"],
    ["ADAM", "First man"],
    ["ABEL", "Second son"],
    ["CAIN", "First son"],
    ["NOAH", "Man with the boat"],
    ["BABEL", "Tower that ended in confusion"],
    ["FLOOD", "Forty days of it"],
    ["SERPENT", "The one with the apple"],
    ["ABRAHAM", "Patriarch asked to leave his country"],
    ["ISAAC", "Abraham's son"],
    ["JACOB", "He wrestled all night"],
    ["JOSEPH", "The one with the coat"],
    ["HYUNDAI", "Korean carmaker behind Genesis"],
    ["SEDAN", "Body style of the G80"],
    ["COUPE", "Two-door body style"],
  ],
  "united airlines": [
    ["UNITED", "Chicago-based airline"],
    ["OHARE", "United's home airport"],
    ["POLARIS", "United's business class"],
    ["PREMIER", "United's frequent flyer status"],
    ["NEWARK", "United hub across the river from Manhattan"],
    ["DENVER", "United hub in the Rockies"],
    ["BOEING", "Maker of much of the fleet"],
    ["ECONOMY", "Back of the plane"],
    ["ALLIANCE", "Star ___, United's network"],
    ["MILES", "What the programme pays in"],
    ["HUB", "Airport an airline builds around"],
  ],
  "high end cards": [
    ["PLATINUM", "Card metal above gold"],
    ["SAPPHIRE", "Chase's premium line"],
    ["CENTURION", "The black card"],
    ["CONCIERGE", "Person the card gives you a number for"],
    ["POINTS", "What the spending earns"],
    ["TRANSFER", "Move points to an airline"],
    ["ANNUAL", "___ fee, the catch"],
    ["PERKS", "Why the fee is worth it, supposedly"],
    ["METAL", "What the premium card is made of"],
    ["CREDIT", "Statement ___, a card benefit"],
    ["CASHBACK", "Simpler kind of reward"],
  ],
  solidcore: [
    ["SOLIDCORE", "Studio chain built on slow reformer work"],
    ["REFORMER", "Machine with a sliding carriage"],
    ["PILATES", "The method behind the machine"],
    ["TEMPO", "How slowly you are told to move"],
    ["SPRING", "What sets the resistance"],
    ["PLANK", "Hold it and shake"],
    ["LUNGE", "Step and drop"],
    ["COACH", "Voice over the music"],
    ["STUDIO", "Where the class happens"],
    ["REPS", "How the set is counted"],
  ],
  yoga: [
    ["ASANA", "A posture"],
    ["VINYASA", "Flowing style linked to breath"],
    ["NAMASTE", "How the class ends"],
    ["SAVASANA", "The lying-down one at the end"],
    ["WARRIOR", "Pose numbered one, two or three"],
    ["CHAKRA", "Energy centre"],
    ["MAT", "What you unroll"],
    ["FLOW", "Sequence of poses"],
    ["BREATH", "What the whole thing is timed to"],
    ["COBRA", "Chest-lifting pose"],
    ["PIGEON", "Hip-opening pose"],
    ["BLOCK", "Foam prop"],
    ["STRAP", "Prop for reaching further"],
    ["TREE", "Balancing pose on one foot"],
  ],
  costco: [
    ["COSTCO", "Warehouse club with the hot dog deal"],
    ["KIRKLAND", "Costco's own label"],
    ["BULK", "How everything is sold"],
    ["MEMBERSHIP", "What you show at the door"],
    ["SAMPLES", "Little cups on the aisle ends"],
    ["ROTISSERIE", "The famous cheap chicken"],
    ["PALLET", "What the goods sit on"],
    ["WAREHOUSE", "What Costco calls its stores"],
    ["RECEIPT", "What gets checked on the way out"],
    ["FOODCOURT", "Where the hot dog is"],
  ],
  vietnamese: [
    ["HOISIN", "Thick sweet sauce for pho"],
    ["SRIRACHA", "Squeeze bottle with the rooster"],
    ["BROTH", "What the bowl is mostly"],
    ["BASIL", "Herb on the side plate"],
    ["LIME", "Wedge you squeeze in"],
    ["CHILI", "Sliced hot on the plate"],
    ["NOODLE", "The other thing in the bowl"],
    ["CAPHE", "Vietnamese coffee"],
    ["SUACHUA", "Vietnamese yoghurt"],
  ],
  "leominster ma": [
    ["LEOMINSTER", "North central Massachusetts city"],
    ["APPLESEED", "Johnny ___, born in Leominster"],
    ["PLASTICS", "Industry Leominster was built on"],
    ["PIONEER", "___ Plastics City, Leominster's nickname"],
    ["SHOLAN", "Leominster's city-owned apple farm"],
    ["DOYLE", "Leominster's field and park"],
    ["MONOOSNOC", "Hill overlooking Leominster"],
    ["FITCHBURG", "Leominster's twin city"],
  ],
  "worcester ma": [
    ["WORCESTER", "Heart of the Commonwealth"],
    ["WOOSOX", "Worcester's ball club"],
    ["POLARPARK", "Where the WooSox play"],
    ["WORMTOWN", "Worcester's nickname"],
    ["HOLYCROSS", "College on Worcester's hill"],
    ["CLARK", "University in Worcester"],
    ["ELMPARK", "One of America's oldest public parks"],
    ["TABLETALK", "Worcester's little pies"],
    ["CANAL", "___ District, Worcester's night out"],
    ["SHREWSBURY", "Worcester street lined with restaurants"],
  ],
  church: [
    ["PEW", "Bench you sit in"],
    ["ALTAR", "Front and centre"],
    ["HYMN", "Sung from the book"],
    ["CHOIR", "The ones in the loft"],
    ["SERMON", "The long part"],
    ["PULPIT", "Where the sermon comes from"],
    ["STEEPLE", "Pointed top"],
    ["PARISH", "The local congregation"],
    ["PSALM", "One of a hundred and fifty"],
    ["LENT", "Forty days of giving something up"],
    ["ADVENT", "Four Sundays of waiting"],
    ["CHAPEL", "Small place of worship"],
    ["DEACON", "One who assists"],
    ["PASTOR", "One who leads"],
    ["LITURGY", "The order of service"],
    ["BAPTISM", "Welcome with water"],
    ["COMMUNION", "Bread and wine"],
    ["NAVE", "Main body of the building"],
    ["OFFERING", "What the plate is for"],
  ],
  "interior design": [
    ["SCONCE", "Light fixed to the wall"],
    ["THROW", "Blanket that lives on the sofa"],
    ["RUNNER", "Long narrow rug"],
    ["VALANCE", "Fabric across the top of a window"],
    ["ACCENT", "___ wall, the painted one"],
    ["PALETTE", "The colours you settled on"],
    ["TEXTURE", "What stops a room looking flat"],
    ["VELVET", "Soft pile fabric"],
    ["LINEN", "Fabric that wrinkles beautifully"],
    ["RATTAN", "Woven cane furniture"],
    ["BOUCLE", "Looped, nubbly upholstery fabric"],
    ["OTTOMAN", "Padded thing you put your feet on"],
    ["CONSOLE", "Narrow table against a wall"],
    ["SIDEBOARD", "Low cabinet in the dining room"],
    ["MOULDING", "Trim where wall meets ceiling"],
    ["SWATCH", "Small sample of the fabric"],
    ["STAGING", "Dressing a house to sell it"],
    ["MIDCENTURY", "Style with tapered wooden legs"],
    ["RUG", "What anchors the seating"],
    ["TRIM", "Paint colour for the woodwork"],
  ],
  iphone: [
    ["IPHONE", "The one in your pocket"],
    ["FACEID", "Unlock by looking"],
    ["SIRI", "The one who mishears you"],
    ["APPSTORE", "Where apps come from"],
    ["ICLOUD", "Where the photos go"],
    ["IMESSAGE", "Blue bubbles"],
    ["WIDGET", "Home screen tile"],
    ["PORTRAIT", "Mode that blurs the background"],
    ["LIGHTNING", "Cable Apple used before USB-C"],
    ["SILENT", "What the little switch does"],
    ["CHARGER", "What is never where you left it"],
    ["SCREEN", "___ time, the weekly report"],
  ],
  "apple watch": [
    ["RINGS", "Three circles to close"],
    ["WORKOUT", "What you forget to start"],
    ["CROWN", "Digital dial on the side"],
    ["HAPTIC", "The tap on your wrist"],
    ["BAND", "Swappable strap"],
    ["ACTIVITY", "The app with the rings"],
    ["ULTRA", "The big rugged model"],
    ["SERIES", "How the models are numbered"],
    ["STEPS", "What it counts all day"],
    ["SLEEP", "What it tracks overnight"],
  ],
  airpods: [
    ["AIRPODS", "Apple's earbuds"],
    ["PODS", "The buds, informally"],
    ["PAIRING", "Connecting them the first time"],
    ["NOISE", "___ cancellation"],
    ["TRANSPARENCY", "Mode that lets the room in"],
    ["STEM", "The bit that sticks down"],
    ["EARTIP", "Silicone piece that seals"],
    ["SPATIAL", "___ audio, sound that moves with your head"],
    ["CHARGE", "What the case does"],
  ],
  dogs: [
    ["LEASH", "Attached to the collar"],
    ["KIBBLE", "Dry food"],
    ["FETCH", "The game with the ball"],
    ["PAW", "Shake it"],
    ["BARK", "Doorbell response"],
    ["PUPPY", "The chewing stage"],
    ["COLLAR", "Where the tags hang"],
    ["TREAT", "Payment for sitting"],
    ["BREED", "Labrador, for one"],
    ["GROOM", "Bath, brush and nails"],
    ["KENNEL", "Where they stay when you travel"],
    ["RESCUE", "Where a lot of them come from"],
    ["BEAGLE", "Small hound with a big nose"],
    ["POODLE", "Curly-coated breed"],
    ["TERRIER", "Small, determined breed group"],
    ["RETRIEVER", "Golden or Labrador"],
    ["MUTT", "Happily mixed breed"],
    ["ZOOMIES", "Sudden sprint round the room"],
    ["CRATE", "Their own little room"],
    ["WAG", "What the tail does"],
  ],
  amex: [
    ["AMEX", "Card company of Platinum and Centurion"],
    ["MEMBERSHIP", "___ Rewards, Amex's points"],
    ["GOLD", "Amex card known for dining and groceries"],
    ["GREEN", "Amex's original card colour"],
    ["RESY", "Restaurant booking service Amex owns"],
    ["CLEAR", "Airport queue-skipping service a card may cover"],
    ["DINING", "Category the Gold card pays extra on"],
    ["CHARGE", "Kind of card paid in full each month"],
  ],
  "chase reserve": [
    ["CHASE", "Bank behind the Sapphire cards"],
    ["RESERVE", "The higher Sapphire tier"],
    ["PREFERRED", "The lower Sapphire tier"],
    ["ULTIMATE", "___ Rewards, Chase's points"],
    ["PRIORITY", "___ Pass, the lounge network"],
    ["HYATT", "Hotel programme Chase points move to"],
    ["TRAVEL", "Portal you can book through"],
  ],
};
