// Short themed answers, three to five letters.
//
// These matter more than the long ones. A crossword is mostly short entries, so
// how much of a grid can be themed is decided almost entirely by how many short
// themed answers there are to choose from.

export const SHARED_SHORT = {
  "rock climbing": [
    ["CAM", "Spring-loaded piece of protection"],
    ["NUT", "Wedge of metal slotted into a crack"],
    ["RACK", "All the gear you carry up"],
    ["SLING", "Loop of webbing"],
    ["TOPO", "Diagram of a route"],
    ["WHIP", "Long, airy fall"],
    ["EDGE", "Thin hold, or what you stand on"],
    ["TAPE", "What goes round split fingertips"],
    ["PAD", "What a boulderer lands on"],
    ["TICK", "Chalk mark showing where to grab"],
  ],
  golf: [
    ["CART", "Ride between shots"],
    ["FLAG", "What marks the hole"],
    ["TURF", "What the divot came out of"],
    ["SAND", "What the bunker is full of"],
    ["WOOD", "Club named for what it used to be"],
    ["CADDY", "Bag carrier, spelled the other way"],
    ["DRIVE", "Tee shot"],
    ["LIP", "Edge of the cup"],
    ["PRO", "The one giving the lesson"],
    ["TEES", "Pegs in the golfer's pocket"],
  ],
  reddit: [
    ["SUBS", "Communities you follow"],
    ["MODS", "The ones who lock the thread"],
    ["POST", "What gets upvoted"],
    ["VOTE", "Up or down"],
    ["USER", "One with a throwaway account"],
    ["LINK", "What the post points at"],
    ["BOTS", "Accounts that reply automatically"],
    ["RULE", "What the sidebar lists"],
  ],
  memes: [
    ["EPIC", "Old internet word for great"],
    ["FAIL", "Word under the video of the wipeout"],
    ["RAGE", "___ comic, an early meme form"],
    ["LORE", "Backstory nobody asked for"],
    ["SIGMA", "Meme label for the lone wolf"],
    ["MEMES", "What the feed is mostly made of"],
    ["GIFS", "Looping clips, in the plural"],
  ],
  korea: [
    ["HAN", "River through Seoul"],
    ["GIM", "Dried seaweed sheet"],
    ["OPPA", "What a younger woman calls an older man"],
    ["KIA", "Korean carmaker"],
    ["JJIGAE", "Korean stew"],
    ["MUKBANG", "Eating broadcast"],
  ],
  japan: [
    ["NORI", "Seaweed around the roll"],
    ["TOFU", "Bean curd"],
    ["MOCHI", "Pounded rice cake"],
    ["GYOZA", "Pan-fried dumpling"],
    ["EDO", "Tokyo, before 1868"],
    ["FUTON", "Mattress you roll away"],
    ["SHOJI", "Paper sliding screen"],
    ["JUDO", "The gentle way"],
    ["KENDO", "Fencing with bamboo swords"],
    ["WAGYU", "Very expensive beef"],
    ["PONZU", "Citrus soy sauce"],
    ["DASHI", "Stock behind most Japanese cooking"],
    ["KATSU", "Breaded cutlet"],
    ["BONSAI", "Tree kept very small on purpose"],
    ["RYOKAN", "Traditional inn"],
    ["YUKATA", "Light summer kimono"],
  ],
  "hong kong": [
    ["MTR", "Hong Kong's metro"],
    ["BUN", "Pineapple ___, a Hong Kong bakery staple"],
    ["SIUMAI", "Pork dumpling on the dim sum trolley"],
    ["CHARSIU", "Barbecued pork"],
    ["YUMCHA", "Going for tea and dim sum"],
    ["TAIPO", "District in the New Territories"],
  ],
  vietnam: [
    ["TET", "Vietnamese new year"],
    ["BUN", "Vietnamese rice noodle"],
    ["BIA", "Beer, in Vietnamese"],
    ["GOI", "___ cuon, the fresh spring roll"],
    ["VIET", "Prefix for the country's people"],
    ["CHA", "___ ca, Hanoi's turmeric fish dish"],
  ],
  pcs: [
    ["LED", "Light in the case"],
    ["RGB", "Lighting nobody strictly needs"],
    ["ATX", "Common case and board size"],
    ["NVME", "Fast drive standard"],
    ["SATA", "Older drive interface"],
    ["DIMM", "What a memory stick is"],
    ["CORE", "One of the CPU's several"],
    ["CLOCK", "Speed in gigahertz"],
    ["WIFI", "No cable needed"],
    ["DOCK", "What a laptop sits in"],
    ["WATT", "Unit on the power supply label"],
    ["HEAT", "What the cooler is fighting"],
  ],
  "video gaming": [
    ["AFK", "Away from keyboard"],
    ["TANK", "Role that soaks the damage"],
    ["HEAL", "What the support does"],
    ["MOBA", "Genre of Dota and its rivals"],
    ["DEMO", "Free slice of a game"],
    ["CRIT", "Extra-damage hit"],
    ["AGGRO", "Attention you have drawn from an enemy"],
    ["PARRY", "Deflect at the right moment"],
    ["DODGE", "Get out of the way"],
    ["META", "What everyone is playing this patch"],
    ["SMURF", "Strong player on a new account"],
    ["FRAG", "A kill, in shooter slang"],
    ["SKIN", "Cosmetic you paid for"],
    ["HUD", "Overlay with your health and ammo"],
    ["MAP", "Where the match takes place"],
    ["PORT", "Version for another platform"],
  ],
  "board games": [
    ["CARD", "What you draw"],
    ["HAND", "What you hold"],
    ["DRAW", "Take from the deck"],
    ["BLUFF", "Play it like you have it"],
    ["SCORE", "What the track records"],
    ["PIECE", "What you move"],
    ["CUBE", "Little wooden resource"],
    ["PIP", "Dot on a die"],
    ["PHASE", "Segment of a turn"],
    ["ENGINE", "What you build in a Euro game"],
  ],
  boston: [
    ["BEAN", "___ town"],
    ["HUB", "What Boston calls itself"],
    ["PIKE", "The Mass ___"],
    ["ZAKIM", "Cable-stayed bridge over the Charles"],
    ["TOBIN", "Bridge to Chelsea"],
    ["ORTIZ", "Big Papi"],
    ["BRADY", "Six-ring quarterback"],
    ["FENS", "Marshy park near the ballpark"],
    ["TPARTY", "1773 harbour protest, familiarly"],
    ["HARBOR", "Where the tea went"],
  ],
  "arlington ma": [
    ["POND", "Spy ___"],
    ["TOWN", "What Arlington is, not a city"],
    ["MASS", "___ Ave, the main drag"],
  ],
  "quincy ma": [
    ["BAY", "Marina ___"],
    ["QUARRY", "Where Quincy's granite came from"],
    ["FORE", "___ River, Quincy's shipbuilding water"],
  ],
  healthcare: [
    ["BED", "Unit of hospital capacity"],
    ["LAB", "Where the blood goes"],
    ["MED", "Short for the thing on the chart"],
    ["DOC", "The one with the stethoscope"],
    ["CARE", "What the whole thing is for"],
    ["PILL", "Tablet"],
    ["TEST", "What the lab runs"],
    ["SCAN", "CT or MRI"],
    ["CODE", "Called overhead in an emergency"],
    ["NOTE", "What the clinician writes"],
    ["PULSE", "Beats per minute"],
    ["FEVER", "Temperature over 100"],
    ["MASK", "Standard on the ward since 2020"],
    ["SWAB", "Stick used for a sample"],
    ["GLOVE", "Put on before every patient"],
    ["VEIN", "Where the needle goes"],
  ],
  "big pharma": [
    ["DRUG", "What the company sells"],
    ["LABEL", "What the FDA approves alongside the drug"],
    ["BRAND", "The expensive name"],
    ["ORAL", "Taken by mouth"],
    ["PRICE", "The part that makes the news"],
    ["TIER", "Where the formulary puts your drug"],
    ["PHASE", "Trials come in three of them"],
  ],
};

export const CLEM_SHORT = {
  programming: [
    ["BIT", "Smallest unit of information"],
    ["BYTE", "Eight of them"],
    ["VOID", "Returns nothing"],
    ["TRUE", "One of two"],
    ["ELSE", "What happens otherwise"],
    ["TYPE", "What the compiler checks"],
    ["ARGS", "What you pass in"],
    ["DIFF", "What the review shows"],
    ["REPO", "Where the code lives"],
    ["FORK", "Your own copy of a project"],
    ["PUSH", "Send commits up"],
    ["MOCK", "Stand-in for a real dependency"],
    ["STUB", "Placeholder implementation"],
    ["TRACE", "Stack ___, printed on a crash"],
    ["JSON", "Braces and quotes"],
    ["YAML", "Config format that cares about indentation"],
    ["HTTP", "Protocol of the web"],
    ["REST", "Style of API"],
    ["CRUD", "Create, read, update, delete"],
    ["HASH", "Fixed-length fingerprint"],
    ["NODE", "Point in a tree or graph"],
    ["QUEUE", "First in, first out"],
    ["ASCII", "Old character set"],
  ],
  finance: [
    ["CASH", "The liquid kind"],
    ["DEBT", "What you owe"],
    ["RISK", "What the model tries to price"],
    ["RATE", "What the central bank sets"],
    ["GAIN", "The good kind of move"],
    ["LOSS", "The other kind"],
    ["FUND", "Pooled investment"],
    ["SHARE", "One slice of a company"],
    ["STOCK", "What the ticker tracks"],
    ["BULL", "Optimist in the market"],
    ["BEAR", "Pessimist in the market"],
    ["SHORT", "Bet that it goes down"],
    ["CAP", "Market ___"],
  ],
  sql: [
    ["ROW", "One record"],
    ["KEY", "What uniquely identifies a row"],
    ["VIEW", "Saved query that behaves like a table"],
    ["ALTER", "Change a table's shape"],
    ["DROP", "Delete the whole table"],
    ["LIKE", "Operator for wildcard matching"],
    ["DESC", "Sort the other way"],
    ["COUNT", "Aggregate that just tallies"],
    ["LEFT", "Kind of join that keeps everything on one side"],
    ["UNION", "Stack two result sets"],
    ["EXISTS", "Check whether a subquery returns anything"],
    ["TEMP", "___ table, gone at the end of the session"],
  ],
  csharp: [
    ["VAR", "Let the compiler work out the type"],
    ["NEW", "Keyword that allocates"],
    ["THIS", "The current instance"],
    ["BASE", "The class you inherited from"],
    ["USING", "Directive at the top of the file"],
    ["TASK", "What an async method returns"],
    ["LIST", "The everyday collection type"],
    ["STATIC", "Belongs to the type, not the instance"],
    ["PUBLIC", "Visible to everyone"],
    ["SEALED", "Cannot be inherited from"],
  ],
  "magic the gathering": [
    ["MILL", "Put cards from library to graveyard"],
    ["RAMP", "Get to more mana faster"],
    ["BOLT", "Lightning ___, three damage"],
    ["FETCH", "Land that finds another land"],
    ["DUAL", "Land that taps for two colours"],
    ["LORD", "Creature that pumps its own kind"],
    ["LIFE", "Starts at twenty"],
    ["WRATH", "Board wipe, classically"],
  ],
  "graphics cards": [
    ["FPS", "Frames per second"],
    ["TDP", "Power the card is rated to draw"],
    ["DLSS", "NVIDIA's upscaler"],
    ["FSR", "AMD's upscaler"],
    ["BOOST", "Clock speed above base"],
    ["TITAN", "NVIDIA's old halo card"],
    ["MINER", "Who bought all the cards"],
    ["DDR", "What the memory standard is called"],
  ],
  dota: [
    ["LANE", "Top, mid or bottom"],
    ["FARM", "Collect gold from creeps"],
    ["ITEM", "What you buy with the gold"],
    ["AEGIS", "What Roshan drops"],
    ["RUNE", "Pickup in the river"],
    ["BLINK", "Dagger that teleports you"],
    ["PUDGE", "Hero with the hook"],
    ["PUSH", "Take the tower"],
  ],
  starcraft: [
    ["APM", "Actions per minute"],
    ["SCV", "Terran worker"],
    ["DRONE", "Zerg worker"],
    ["PROBE", "Protoss worker"],
    ["NEXUS", "Protoss main building"],
    ["MULE", "Terran unit called down for mining"],
    ["ARMY", "What the macro pays for"],
    ["TECH", "Move up the building tree"],
    ["DROP", "Attack from a transport"],
    ["HYDRA", "Zerg ranged unit, familiarly"],
  ],
  "elden ring": [
    ["RUNE", "What the enemies drop"],
    ["SITE", "___ of Grace"],
    ["PARRY", "Well-timed shield move"],
    ["TORRENT", "Your spectral steed"],
    ["RADAHN", "Starscourge general"],
    ["MOHG", "Lord of Blood"],
    ["LORE", "What the item descriptions are for"],
  ],
  "red dead redemption": [
    ["GANG", "Van der Linde's crew"],
    ["TRAIN", "Thing worth robbing"],
    ["DEER", "Hunt it for the pelt"],
    ["JOHN", "Marston of the gang"],
    ["SADIE", "Adler, who joins the camp"],
    ["MICAH", "The one you should not trust"],
    ["HOSEA", "The gang's other planner"],
    ["CORE", "Health, stamina or dead eye meter"],
  ],
  "sysadmin and helpdesk": [
    ["LOG", "First place to look"],
    ["NIC", "Network card"],
    ["RAID", "Disks pretending to be one disk"],
    ["SUDO", "Do it as the superuser"],
    ["ROOT", "The account with everything"],
    ["USER", "The one filing the ticket"],
    ["SSH", "Secure shell"],
    ["RDP", "Remote desktop protocol"],
    ["DHCP", "What hands out addresses"],
    ["SPAM", "What the filter catches"],
    ["PHISH", "Email pretending to be your bank"],
    ["MFA", "Second factor"],
    ["SSO", "Sign in once for everything"],
    ["IMAGE", "Standard build for a laptop"],
  ],
  "hospital data": [
    ["ICD", "Diagnosis code set"],
    ["CPT", "Procedure code set"],
    ["NPI", "Provider's national identifier"],
    ["MRN", "Number that identifies a patient in a hospital"],
    ["ETL", "Extract, transform, load"],
    ["PHI", "Protected health information"],
    ["HIPAA", "The privacy law"],
    ["CHARGE", "What lands on the bill"],
    ["RESULT", "What comes back from the lab"],
    ["LOINC", "Code set for lab observations"],
  ],
};

export const LORI_SHORT = {
  instagram: [
    ["BIO", "Line under the handle"],
    ["POST", "What you put up"],
    ["FEED", "What you scroll"],
    ["SAVE", "Keep a post for later"],
    ["LIVE", "Going ___, broadcasting now"],
    ["SHARE", "Send it on"],
  ],
  travel: [
    ["TSA", "Who checks your bag"],
    ["SEAT", "27B, say"],
    ["FARE", "What the ticket costs"],
    ["TRIP", "The whole thing"],
    ["TOUR", "Guided version"],
    ["PACK", "Do it the night before"],
    ["HOTEL", "Where you check in"],
    ["FERRY", "Boat on a timetable"],
    ["TAXI", "How you get from the airport"],
  ],
  alnylam: [
    ["RNA", "The molecule Alnylam works on"],
    ["LAB", "Where the work happens"],
  ],
  genesis: [
    ["ARK", "Noah's build"],
    ["EVE", "First woman"],
    ["RIB", "What she was made from"],
    ["LOT", "He was told not to look back"],
  ],
  "united airlines": [
    ["JET", "What you fly on"],
    ["CREW", "Who works the cabin"],
    ["WING", "Where the flaps are"],
    ["ROW", "Where your seat is"],
    ["LAND", "End of the flight"],
    ["FUEL", "What gets topped up at the gate"],
  ],
  "high end cards": [
    ["FEE", "The annual one"],
    ["APR", "Rate on a balance"],
    ["SWIPE", "Old way to pay"],
    ["TAP", "New way to pay"],
    ["LIMIT", "How much you can spend"],
    ["BANK", "Who issues the card"],
  ],
  solidcore: [
    ["ABS", "What the class is after"],
    ["SET", "Block of reps"],
    ["SLOW", "How you are told to move"],
    ["BURN", "The point of it"],
  ],
  yoga: [
    ["POSE", "One shape in the sequence"],
    ["CALM", "What you leave with"],
    ["BEND", "Forward ___"],
    ["TWIST", "Seated spinal move"],
    ["HIP", "___ opener"],
  ],
  costco: [
    ["CART", "Oversized trolley"],
    ["GAS", "Cheapest thing at the front of the lot"],
    ["TUB", "How the sour cream comes"],
    ["HOTDOG", "A dollar fifty, with a soda"],
  ],
  vietnamese: [
    ["MINT", "Herb on the plate"],
    ["HERB", "What comes on the side"],
    ["RICE", "The other staple"],
    ["BOWL", "What it all arrives in"],
    ["SOUP", "What pho is, technically"],
  ],
  "worcester ma": [
    ["WOO", "Worcester, in a nickname"],
    ["PIE", "What Table Talk makes"],
    ["HILL", "What Holy Cross sits on"],
  ],
  "leominster ma": [
    ["FARM", "Sholan ___, the city orchard"],
    ["ROUTE", "___ 2, the road north of town"],
  ],
  church: [
    ["PEW", "Where you sit"],
    ["HYMN", "Number on the board"],
    ["AMEN", "Last word"],
    ["BELL", "What the tower holds"],
    ["ROBE", "What the choir wears"],
    ["CROSS", "Above the altar"],
    ["SAINT", "One with a feast day"],
    ["GRACE", "Said before eating"],
    ["FAITH", "The point of it"],
    ["PRAY", "What you came to do"],
    ["CREED", "What the congregation recites"],
    ["MASS", "The service, in some churches"],
  ],
  "interior design": [
    ["LAMP", "Light you can move"],
    ["VASE", "For the stems"],
    ["TILE", "Backsplash unit"],
    ["PAINT", "First decision"],
    ["SHELF", "Where the books go"],
    ["NOOK", "Small useful corner"],
    ["LOFT", "Open-plan look"],
    ["TONE", "Warm or cool"],
    ["HUE", "The colour itself"],
    ["WOOD", "Oak, walnut or ash"],
  ],
  iphone: [
    ["APP", "Tap to open"],
    ["CASE", "What stops the crack"],
    ["LOCK", "___ screen"],
    ["PHOTO", "What the camera makes"],
    ["VIDEO", "What the camera also makes"],
    ["SWIPE", "How you dismiss it"],
  ],
  "apple watch": [
    ["ECG", "Heart reading on your wrist"],
    ["FACE", "What you customise"],
    ["DIAL", "Turn the crown to do this"],
    ["WRIST", "Where it lives"],
    ["TIMER", "Set it for the pasta"],
    ["ALARM", "What buzzes you awake"],
  ],
  airpods: [
    ["EAR", "Where they go"],
    ["POD", "One of the pair"],
    ["BUDS", "What they are, generically"],
    ["MUTE", "Kill the sound"],
  ],
  dogs: [
    ["PUP", "Young one"],
    ["FUR", "What sheds on everything"],
    ["TOY", "Squeaky thing"],
    ["BONE", "Classic chew"],
    ["BOWL", "Food and water go in it"],
    ["WALK", "The best word in the language"],
    ["SIT", "First command taught"],
    ["LAP", "Where a small one ends up"],
    ["DIG", "What ruins the garden"],
    ["LICK", "How you get woken up"],
    ["HOWL", "Response to a siren"],
    ["LEAD", "Leash, in Britain"],
  ],
  amex: [
    ["POINT", "One unit of Membership Rewards"],
    ["LOUNGE", "Centurion ___"],
  ],
  "chase reserve": [
    ["CARD", "What is in your wallet"],
    ["PAY", "What it is for"],
  ],
};
