// Transit vocabulary: the rail networks both players know, station by station.
//
// Station names are run together, the way any crossword handles a two-word
// proper noun -- TAI KOO becomes TAIKOO. Names over fifteen letters are entered
// by the part people actually say (GOVERNMENT for Government Center), with the
// rest of the name in the clue.
//
// These are shared topics: both players get all of them.

export const TRANSIT_THEMES = {
  "hong kong mtr": [
    // Island line, west to east
    ["KENNEDYTOWN", "Western end of the Island line"],
    ["HKU", "Island line stop under the university"],
    ["SAIYINGPUN", "Island line stop west of Sheung Wan"],
    ["SHEUNGWAN", "Island line stop by the dried seafood shops"],
    ["CENTRAL", "Interchange under the banks"],
    ["ADMIRALTY", "Four-line interchange east of the business district"],
    ["WANCHAI", "Island line stop by the convention centre"],
    ["CAUSEWAYBAY", "Island line stop where everyone shops"],
    ["TINHAU", "Island line stop named for a sea goddess"],
    ["FORTRESSHILL", "Island line stop before North Point"],
    ["NORTHPOINT", "Where the Island and Tseung Kwan O lines meet"],
    ["QUARRYBAY", "Interchange east of North Point"],
    ["TAIKOO", "Island line stop under the big mall"],
    ["SAIWANHO", "Island line stop east of Tai Koo"],
    ["SHAUKEIWAN", "Island line stop by the typhoon shelter"],
    ["HENGFACHUEN", "Island line stop at a seaside estate"],
    ["CHAIWAN", "Eastern end of the Island line"],
    // Tsuen Wan line
    ["TSIMSHATSUI", "Kowloon stop at the harbourfront"],
    ["JORDAN", "Tsuen Wan line stop north of the harbour"],
    ["YAUMATEI", "Interchange near the jade market"],
    ["MONGKOK", "Interchange in the densest shopping streets"],
    ["PRINCEEDWARD", "Interchange one stop north of Mong Kok"],
    ["SHAMSHUIPO", "Stop for the electronics stalls"],
    ["CHEUNGSHAWAN", "Tsuen Wan line stop in northwest Kowloon"],
    ["LAICHIKOK", "Tsuen Wan line stop near the bridge"],
    ["MEIFOO", "Interchange at a huge private estate"],
    ["LAIKING", "Where the Tsuen Wan and Tung Chung lines meet"],
    ["KWAIFONG", "Tsuen Wan line stop in Kwai Tsing"],
    ["KWAIHING", "Tsuen Wan line stop north of Kwai Fong"],
    ["TAIWOHAU", "Last stop before the Tsuen Wan terminus"],
    ["TSUENWAN", "New town at the end of its own line"],
    // Kwun Tong line
    ["WHAMPOA", "Eastern terminus of the Kwun Tong line"],
    ["HOMANTIN", "Kowloon interchange with the Tuen Ma line"],
    ["SHEKKIPMEI", "Kwun Tong line stop by the old estate"],
    ["KOWLOONTONG", "Interchange with the East Rail line"],
    ["LOKFU", "Kwun Tong line stop with a mall on top"],
    ["WONGTAISIN", "Kwun Tong line stop by the busy temple"],
    ["DIAMONDHILL", "Interchange by the Chi Lin Nunnery"],
    ["CHOIHUNG", "Kwun Tong line stop named for a rainbow"],
    ["KOWLOONBAY", "Kwun Tong line stop in the industrial east"],
    ["NGAUTAUKOK", "Kwun Tong line stop before the terminus"],
    ["KWUNTONG", "Stop that gave its line the name"],
    ["LAMTIN", "Kwun Tong line stop before Yau Tong"],
    ["YAUTONG", "Interchange in the far east of Kowloon"],
    ["TIUKENGLENG", "Interchange at the edge of Tseung Kwan O"],
    // Tseung Kwan O line
    ["TSEUNGKWANO", "New town with a line of its own"],
    ["HANGHAU", "Stop in the middle of Tseung Kwan O"],
    ["POLAM", "Northern terminus in Tseung Kwan O"],
    ["LOHASPARK", "Seaside branch terminus in Tseung Kwan O"],
    // Tung Chung line and Airport Express
    ["HONGKONG", "Airport Express terminus under the towers"],
    ["OLYMPIC", "Tung Chung line stop named for the games"],
    ["NAMCHEONG", "Where the Tung Chung and Tuen Ma lines meet"],
    ["TSINGYI", "Island interchange on the way to the airport"],
    ["SUNNYBAY", "Interchange for the Disneyland branch"],
    ["TUNGCHUNG", "Lantau terminus near the cable car"],
    ["ASIAWORLDEXPO", "Last stop on the Airport Express"],
    ["DISNEYLAND", "End of the shortest line, with mouse-shaped windows"],
    // Tuen Ma line
    ["WUKAISHA", "Northern terminus of the Tuen Ma line"],
    ["MAONSHAN", "Tuen Ma line stop under the mountain"],
    ["HENGON", "Tuen Ma line stop in Ma On Shan"],
    ["TAISHUIHANG", "Tuen Ma line stop south of Heng On"],
    ["SHEKMUN", "Tuen Ma line stop in eastern Sha Tin"],
    ["CITYONE", "Tuen Ma line stop named for an estate"],
    ["SHATINWAI", "Tuen Ma line stop in Sha Tin"],
    ["CHEKUNGTEMPLE", "Tuen Ma line stop named for a shrine"],
    ["TAIWAI", "Big interchange at the south end of Sha Tin"],
    ["HINKENG", "Tuen Ma line stop south of Tai Wai"],
    ["KAITAK", "Tuen Ma line stop on the old airport site"],
    ["SUNGWONGTOI", "Tuen Ma line stop named for a rock"],
    ["TOKWAWAN", "Tuen Ma line stop in old Kowloon"],
    ["HUNGHOM", "Interchange where trains north used to start"],
    ["AUSTIN", "Tuen Ma line stop by the west Kowloon park"],
    ["TSUENWANWEST", "Tuen Ma line stop out by the water"],
    ["KAMSHEUNGROAD", "Tuen Ma line stop in the New Territories"],
    ["YUENLONG", "Tuen Ma line stop in the northwest"],
    ["LONGPING", "Tuen Ma line stop beside Yuen Long"],
    ["TINSHUIWAI", "Tuen Ma line stop in a northwestern new town"],
    ["SIUHONG", "Last Tuen Ma line stop before the terminus"],
    ["TUENMUN", "Western terminus of the Tuen Ma line"],
    // East Rail line
    ["EXHIBITION", "___ Centre, the East Rail stop under the harbour"],
    ["MONGKOKEAST", "East Rail stop beside the shopping district"],
    ["SHATIN", "East Rail stop in the biggest new town"],
    ["FOTAN", "East Rail stop north of the new town"],
    ["RACECOURSE", "East Rail stop that opens on race days only"],
    ["UNIVERSITY", "East Rail stop serving CUHK"],
    ["TAIPOMARKET", "East Rail stop in Tai Po"],
    ["TAIWO", "East Rail stop north of Tai Po Market"],
    ["FANLING", "East Rail stop in the far north"],
    ["SHEUNGSHUI", "Last stop before the border"],
    ["LOWU", "Border crossing at the end of the East Rail line"],
    ["LOKMACHAU", "The other border terminus"],
    // South Island line
    ["OCEANPARK", "South Island line stop at the theme park"],
    ["WONGCHUKHANG", "South Island line stop in the old industrial south"],
    ["LEITUNG", "South Island line stop on Ap Lei Chau"],
    ["SOUTHHORIZONS", "Southern terminus on Ap Lei Chau"],
    ["OCTOPUS", "Card tapped at the gate"],
  ],

  mbta: [
    // Red line
    ["ALEWIFE", "Northwestern end of the Red line"],
    ["DAVIS", "Red line stop in Somerville"],
    ["PORTER", "Red line stop with the very long escalator"],
    ["HARVARD", "Red line stop in the middle of Cambridge"],
    ["KENDALL", "Red line stop by MIT"],
    ["CHARLES", "Red line stop by the hospital and the river"],
    ["PARKSTREET", "Where the Red and Green lines meet"],
    ["DOWNTOWN", "___ Crossing, where the Red and Orange lines meet"],
    ["SOUTHSTATION", "Red line stop at the big rail terminal"],
    ["BROADWAY", "Red line stop in South Boston"],
    ["ANDREW", "Red line stop in Dorchester"],
    ["SAVINHILL", "Red line stop on the Ashmont branch"],
    ["FIELDSCORNER", "Red line stop in Dorchester"],
    ["SHAWMUT", "Last stop before Ashmont"],
    ["ASHMONT", "End of one Red line branch"],
    ["NORTHQUINCY", "First Red line stop in Quincy"],
    ["WOLLASTON", "Red line stop by the beach"],
    ["QUINCYCENTER", "Red line stop downtown in Quincy"],
    ["QUINCYADAMS", "Red line stop with the big garage"],
    ["BRAINTREE", "End of the other Red line branch"],
    // Mattapan trolley
    ["CEDARGROVE", "First stop on the Mattapan trolley"],
    ["BUTLER", "Stop on the Mattapan trolley"],
    ["VALLEYROAD", "Stop on the Mattapan trolley"],
    ["CAPENSTREET", "Last stop before the Mattapan terminus"],
    ["MATTAPAN", "End of the old trolley line"],
    // Orange line
    ["OAKGROVE", "Northern end of the Orange line"],
    ["MALDENCENTER", "Orange line stop north of Wellington"],
    ["WELLINGTON", "Orange line stop in Medford"],
    ["ASSEMBLY", "Newest Orange line stop, in Somerville"],
    ["SULLIVAN", "___ Square, on the Orange line"],
    ["COMMUNITY", "___ College, on the Orange line"],
    ["NORTHSTATION", "Where the Orange and Green lines meet the trains"],
    ["HAYMARKET", "Orange line stop by the produce stalls"],
    ["STATE", "Where the Orange and Blue lines meet"],
    ["CHINATOWN", "Orange line stop by the gate"],
    ["TUFTSMEDICAL", "Orange line stop by the hospital"],
    ["BACKBAY", "Orange line stop in the brownstones"],
    ["MASSAVE", "Orange line stop on the big avenue"],
    ["RUGGLES", "Orange line stop by Northeastern"],
    ["ROXBURYCROSSING", "Orange line stop in Roxbury"],
    ["JACKSONSQUARE", "Orange line stop in Jamaica Plain"],
    ["STONYBROOK", "Orange line stop in Jamaica Plain"],
    ["GREENSTREET", "Last Orange line stop before the end"],
    ["FORESTHILLS", "Southern end of the Orange line"],
    // Blue line
    ["BOWDOIN", "Western end of the Blue line"],
    ["GOVERNMENT", "___ Center, where the Blue and Green lines meet"],
    ["AQUARIUM", "Blue line stop on the waterfront"],
    ["MAVERICK", "Blue line stop in East Boston"],
    ["WOODISLAND", "Blue line stop past the airport"],
    ["ORIENTHEIGHTS", "Blue line stop in East Boston"],
    ["SUFFOLKDOWNS", "Blue line stop at the old racetrack"],
    ["BEACHMONT", "Blue line stop in Revere"],
    ["REVEREBEACH", "Blue line stop by the sand"],
    ["WONDERLAND", "Northern end of the Blue line"],
    // Green line, core and the northern extension
    ["MEDFORDTUFTS", "Northern end of the Green line extension"],
    ["BALLSQUARE", "Green line stop in Somerville"],
    ["MAGOUNSQUARE", "Green line stop in Somerville"],
    ["GILMANSQUARE", "Green line stop in Somerville"],
    ["UNIONSQUARE", "End of the Green line's Somerville branch"],
    ["LECHMERE", "Green line stop by the arena side of the river"],
    ["SCIENCEPARK", "Green line stop by the museum"],
    ["BOYLSTON", "Green line stop at the corner of the Common"],
    ["ARLINGTON", "Green line stop by the Public Garden"],
    ["COPLEY", "Green line stop by the library"],
    ["HYNES", "Green line stop by the convention centre"],
    ["KENMORE", "Green line stop near the ballpark"],
    ["PRUDENTIAL", "Green line stop under the tower"],
    ["SYMPHONY", "Green line stop by the concert hall"],
    ["NORTHEASTERN", "First stop on the E branch"],
    ["MFA", "E branch stop at the art museum"],
    ["LONGWOOD", "Stop in the hospital district"],
    ["BRIGHAMCIRCLE", "E branch stop by the hospital"],
    ["FENWOOD", "___ Road, on the E branch"],
    ["MISSIONPARK", "E branch stop in Mission Hill"],
    ["RIVERWAY", "E branch stop on the parkway"],
    ["HEATHSTREET", "End of the E branch"],
    // B branch
    ["BLANDFORD", "First B branch stop past Kenmore"],
    ["AMORY", "B branch stop in Allston"],
    ["BABCOCK", "B branch stop by the university"],
    ["PACKARDS", "___ Corner, on the B branch"],
    ["GRIGGS", "B branch stop in Allston"],
    ["ALLSTON", "B branch stop in its own neighbourhood"],
    ["WARREN", "B branch stop in Allston"],
    ["SUTHERLAND", "B branch stop in Brighton"],
    ["CHISWICK", "B branch stop in Brighton"],
    ["CHESTNUTHILL", "Avenue stop on the B branch"],
    ["SOUTHSTREET", "Last B branch stop before the college"],
    ["BOSTONCOLLEGE", "Western end of the B branch"],
    // C branch
    ["STMARYS", "First C branch stop in Brookline"],
    ["HAWES", "C branch stop in Brookline"],
    ["KENT", "C branch stop in Brookline"],
    ["COOLIDGE", "___ Corner, the busiest C branch stop"],
    ["SUMMIT", "C branch stop in Brookline"],
    ["BRANDONHALL", "C branch stop in Brookline"],
    ["FAIRBANKS", "C branch stop in Brookline"],
    ["TAPPAN", "C branch stop in Brookline"],
    ["DEANROAD", "C branch stop in Brookline"],
    ["ENGLEWOOD", "Last C branch stop before the circle"],
    ["CLEVELANDCIRCLE", "Western end of the C branch"],
    // D branch
    ["FENWAY", "First D branch stop"],
    ["BROOKLINE", "___ Village, on the D branch"],
    ["BEACONSFIELD", "D branch stop in Brookline"],
    ["RESERVOIR", "D branch stop by the water"],
    ["NEWTONCENTRE", "D branch stop in Newton"],
    ["NEWTONHIGHLANDS", "D branch stop in Newton"],
    ["ELIOT", "D branch stop in Newton"],
    ["WABAN", "D branch stop in Newton"],
    ["WOODLAND", "Last D branch stop before the end"],
    ["RIVERSIDE", "Western end of the D branch"],
    // Silver line and the rest
    ["COURTHOUSE", "Silver line stop in the Seaport"],
    ["WORLDTRADE", "Silver line stop in the Seaport"],
    ["CHELSEA", "Northern end of the Silver line"],
    ["BOXDISTRICT", "Silver line stop in Chelsea"],
    ["BELLINGHAM", "___ Square, on the Silver line"],
    ["CHARLIECARD", "Plastic you tap at the gate"],
    ["INBOUND", "Toward the middle of the city"],
    ["OUTBOUND", "Away from the middle of the city"],
  ],

  "japan rail": [
    ["SHINKANSEN", "The fast train, by its own name"],
    ["NOZOMI", "Fastest service down the Tokaido line"],
    ["HIKARI", "The middle-speed bullet service"],
    ["KODAMA", "The all-stations bullet service"],
    ["YAMANOTE", "Loop line round central Tokyo"],
    ["CHUO", "Rapid line straight across Tokyo"],
    ["SOBU", "Line across Tokyo to Chiba"],
    ["KEIYO", "Line out to the bay and the mouse"],
    ["SAIKYO", "Line up Tokyo's western side"],
    ["JOBAN", "Line north out of Ueno"],
    ["TOKAIDO", "Main line between Tokyo and Osaka"],
    ["TOHOKU", "Bullet line to the north"],
    ["SANYO", "Bullet line west of Osaka"],
    ["RAILPASS", "What a visitor buys for a fortnight"],
    ["GREENCAR", "The first-class carriage"],
    ["EKIBEN", "Boxed meal bought on the platform"],
    ["SUICA", "Penguin-branded tap card"],
    ["PASMO", "The other Tokyo tap card"],
    ["TOKYO", "Where the bullet lines all begin"],
    ["SHINJUKU", "Busiest station in the world"],
    ["SHIBUYA", "Loop line stop at the famous crossing"],
    ["IKEBUKURO", "Big loop line stop in the north"],
    ["UENO", "Loop line stop by the park and the zoo"],
    ["AKIHABARA", "Loop line stop for electronics"],
    ["SHINAGAWA", "Southern bullet train stop in Tokyo"],
    ["KANDA", "Loop line stop north of Tokyo station"],
    ["YURAKUCHO", "Loop line stop between Tokyo and Shimbashi"],
    ["SHIMBASHI", "Loop line stop with the old locomotive"],
    ["HAMAMATSUCHO", "Loop line stop for the monorail"],
    ["TAMACHI", "Loop line stop south of Hamamatsucho"],
    ["OSAKI", "Loop line stop in the southwest"],
    ["GOTANDA", "Loop line stop north of Osaki"],
    ["MEGURO", "Loop line stop in southwest Tokyo"],
    ["EBISU", "Loop line stop named after a beer"],
    ["HARAJUKU", "Loop line stop for the shrine and the fashion"],
    ["YOYOGI", "Loop line stop by the big park"],
    ["NIPPORI", "Loop line stop for the Skyliner"],
    ["TABATA", "Loop line stop in the north"],
    ["SUGAMO", "Loop line stop called the old ladies' Harajuku"],
    ["KOMAGOME", "Loop line stop in northern Tokyo"],
    ["SHINOSAKA", "Where the bullet train stops for Osaka"],
    ["KYOTO", "Bullet train stop for the temples"],
    ["NAGOYA", "Bullet train stop between the two big cities"],
    ["HAKATA", "Western end of the bullet line"],
    ["SENDAI", "Biggest stop on the northern bullet line"],
    ["NARITA", "Where the express from the airport starts"],
  ],

  "seoul subway": [
    ["GANGNAM", "Line 2 stop south of the river"],
    ["HONGDAE", "University area on line 2, informally"],
    ["MYEONGDONG", "Line 4 stop for the shopping"],
    ["JAMSIL", "Line 2 stop by the tallest tower"],
    ["ITAEWON", "Line 6 stop for the foreign quarter"],
    ["SINCHON", "Line 2 stop by the universities"],
    ["DONGDAEMUN", "Stop at the old east gate"],
    ["GWANGHWAMUN", "Line 5 stop by the palace gate"],
    ["EULJIRO", "___ 3-ga, a central interchange"],
    ["JONGNO", "___ 3-ga, three lines crossing downtown"],
    ["YEOKSAM", "Line 2 stop in the office district"],
    ["SAMSEONG", "Line 2 stop by the exhibition centre"],
    ["SEOLLEUNG", "Line 2 stop by the royal tombs"],
    ["APGUJEONG", "Line 3 stop for the boutiques"],
    ["YEOUIDO", "Island stop for the assembly and the banks"],
    ["HAPJEONG", "Interchange west of Hongdae"],
    ["SANGSU", "Line 6 stop by the river cafes"],
    ["SADANG", "Busy southern interchange"],
    ["GANGBYEON", "Line 2 stop by the river"],
    ["WANGSIMNI", "Four-line interchange in the east"],
    ["KONKUK", "___ University, a line 2 stop"],
    ["ANGUK", "Line 3 stop for the old hanok village"],
    ["NOWON", "Interchange in the far northeast"],
    ["SILLIM", "Line 2 stop in the southwest"],
    ["TMONEY", "Card tapped on the turnstile"],
  ],

  busan: [
    ["HAEUNDAE", "The city's famous beach"],
    ["GWANGALLI", "Beach under the lit-up bridge"],
    ["SEOMYEON", "Downtown interchange of lines 1 and 2"],
    ["NAMPO", "Line 1 stop for the old downtown"],
    ["JAGALCHI", "The big fish market"],
    ["BEOMEOSA", "Mountain temple at the end of line 1"],
    ["GUPO", "Line 3 stop by the river"],
    ["SASANG", "Western interchange with the light rail"],
    ["DONGNAE", "Northern interchange and hot spring district"],
    ["YEONSAN", "Interchange of lines 1 and 3"],
    ["CENTUM", "___ City, the convention district"],
    ["GAMCHEON", "The painted hillside village"],
    ["TAEJONGDAE", "Cliffs at the end of Yeongdo"],
    ["MILMYEON", "Cold wheat noodles, the local dish"],
    ["GIMHAE", "Where the airport is"],
    ["BIFF", "The city's film festival, in short"],
    ["SEAGULL", "The baseball team's crowd, famously loud"],
  ],

  "nyc subway": [
    ["TIMESSQUARE", "Busiest station in the system"],
    ["GRANDCENTRAL", "Station under the famous ceiling"],
    ["UNIONSQUARE", "Big interchange at 14th Street"],
    ["PENNSTATION", "Station under the arena"],
    ["HERALD", "___ Square, at 34th Street"],
    ["COLUMBUSCIRCLE", "Station at the corner of the park"],
    ["FULTON", "Downtown interchange, rebuilt with an oculus"],
    ["CANAL", "Station between SoHo and Chinatown"],
    ["BOWERY", "Quiet J and Z stop on the Lower East Side"],
    ["ASTOR", "___ Place, by the cube"],
    ["DELANCEY", "Lower East Side stop by the bridge"],
    ["BRYANT", "___ Park, behind the library"],
    ["CHAMBERS", "Stop by City Hall"],
    ["WALLSTREET", "Stop in the financial district"],
    ["BARCLAYS", "Brooklyn stop under the arena"],
    ["BEDFORD", "First Brooklyn stop on the L"],
    ["ATLANTIC", "___ Avenue, Brooklyn's big interchange"],
    ["CONEYISLAND", "End of four lines, by the boardwalk"],
    ["FLUSHING", "Eastern end of the 7"],
    ["JAMAICA", "Queens hub for the trains to the airport"],
    ["ROCKEFELLER", "Midtown stop under the plaza"],
    ["YANKEESTADIUM", "Bronx stop for the ball game"],
    ["LEXINGTON", "___ Avenue, on the East Side"],
    ["METROCARD", "The yellow swipe, now being retired"],
    ["OMNY", "Tap-to-pay that replaced the swipe"],
    ["EXPRESS", "The train that skips your stop"],
    ["LOCAL", "The train that does not"],
  ],
};

// Station names run long -- of the 328 above, only 37 are five letters or under,
// and density tracks the short ones. This is the fill that lets a transit topic
// show up in a 3x3 at all.
export const TRANSIT_SHORT = {
  "hong kong mtr": [
    ["MTR", "The railway, in short"],
    ["LRT", "Light rail out in the northwest"],
    ["EXIT", "Lettered way up to the street"],
    ["GATE", "What the card opens"],
    ["TAP", "What you do with the card"],
    ["FARE", "What the machine deducts"],
    ["LINE", "One colour on the map"],
    ["STOP", "One of the ninety-odd on the network"],
    ["TRAIN", "What comes every two minutes"],
    ["MIND", "___ the gap"],
    ["GAP", "What the announcement says to mind"],
    ["QUEUE", "Orderly thing on the platform"],
  ],
  mbta: [
    ["JFK", "___/UMass, on the Red line"],
    ["TEE", "The system, spelled out"],
    ["BUS", "What the Silver line really is"],
    ["FARE", "What the CharlieCard pays"],
    ["STOP", "One of the hundred-odd on the subway"],
    ["RIDE", "What the monthly pass buys"],
    ["LATE", "What the Green line often is"],
    ["RAIL", "Commuter ___, out to the suburbs"],
    ["LINE", "Red, Orange, Blue or Green"],
    ["TRACK", "What the trolley runs on"],
    ["SEAT", "What nobody gets at rush hour"],
    ["STOPS", "What the local one makes"],
  ],
  "japan rail": [
    ["EKI", "Station, over there"],
    ["SEN", "Line, over there"],
    ["LOOP", "What the Yamanote is"],
    ["GATE", "What the ticket slides into"],
    ["FARE", "What the machine works out"],
    ["BENTO", "Boxed meal for the journey"],
    ["OSAKA", "Second city on the main line"],
    ["NARA", "Old capital on a branch line"],
    ["KOBE", "Port city on the Sanyo line"],
    ["MITO", "Joban line city north of the capital"],
    ["RAPID", "Service that skips the small stations"],
  ],
  "seoul subway": [
    ["KTX", "The country's bullet train"],
    ["LINE", "Numbered route on the map"],
    ["FARE", "What the card deducts"],
    ["GATE", "What you tap through"],
    ["SEOUL", "City the whole network serves"],
    ["SUWON", "Line 1 city to the south"],
    ["BUS", "What runs once the trains stop"],
    ["CARD", "What T-money is on"],
  ],
  busan: [
    ["SEA", "What the city is strung along"],
    ["PORT", "The country's biggest"],
    ["LINE", "One of the four on the metro"],
    ["FISH", "What Jagalchi is full of"],
    ["BEACH", "What Haeundae is"],
    ["KTX", "Three hours from the capital on it"],
    ["SOUTH", "Where the city sits in the country"],
  ],
  "nyc subway": [
    ["MTA", "The authority that runs it"],
    ["IRT", "The old numbered division"],
    ["BMT", "One of the old lettered divisions"],
    ["FARE", "What the turnstile takes"],
    ["STOP", "One of four hundred and seventy-two"],
    ["CAR", "One of ten on the train"],
    ["RAT", "Platform wildlife"],
    ["DOWN", "___town, one of the two directions"],
    ["UPTOWN", "The other direction"],
    ["SWIPE", "What the yellow card wanted"],
  ],
};
