// Extra themed answers, added after the first bank was generated.
//
// Density tracks how many themed answers are three to five letters, not the
// total, so this file leans hard that way: it exists to top up the topics that
// were thin at the lengths a small grid is actually made of.
//
// Keys must match the topic names already in themes-shared / themes-clem /
// themes-lori -- these are merged into those sets, not listed separately.

export const SHARED_EXTRA = {
  "hong kong": [
    ["STAR", "___ Ferry, across the harbour"],
    ["PEAK", "The ___ Tram, up to the view"],
    ["MTR", "Railway under the harbour"],
    ["JUNK", "Red-sailed boat in the bay"],
    ["TRAM", "Double-decker rattling along Hong Kong Island"],
    ["NEON", "What used to light Nathan Road"],
    ["WAN", "___ Chai, on the island"],
    ["CHAI", "Wan ___, the nightlife district"],
    ["SHA", "___ Tin, in the New Territories"],
    ["KWAI", "___ Chung, where the containers stack up"],
    ["OCTO", "___pus card, tapped on every ride"],
    ["BUN", "Pineapple ___, containing no pineapple"],
    ["MTRS", "The railway's lines, collectively"],
    ["WONTON", "Dumpling floating in the noodle soup"],
    ["CONGEE", "Rice porridge for breakfast"],
    ["EGGTART", "Custard in a flaky shell"],
    ["MILKTEA", "Strong brew strained through a stocking"],
    ["LANTAU", "Island with the big Buddha"],
    ["HARBOUR", "What Victoria's name is on"],
    ["MIDLEVELS", "Neighbourhood served by an outdoor escalator"],
  ],
  boston: [
    ["SOX", "Fenway's team, in short"],
    ["HUB", "The ___ of the Universe"],
    ["BEAN", "___ Town"],
    ["PIKE", "The Mass ___, heading west"],
    ["TEA", "What went into the harbor in 1773"],
    ["BAY", "Back ___, of the brownstones"],
    ["PARK", "Fenway ___"],
    ["CITGO", "Sign glowing over Kenmore"],
    ["GREEN", "___ Line, the slow one"],
    ["RED", "___ Line, out to Alewife"],
    ["COMMON", "Oldest public park in the country"],
    ["BEACON", "___ Hill, gaslit and steep"],
    ["CHARLES", "River between the two cities"],
    ["WICKED", "Very, hereabouts"],
    ["CHOWDA", "Clam soup, said locally"],
    ["SOUTHIE", "South Boston, to anyone from there"],
    ["SEAPORT", "The glassy new waterfront"],
    ["NORTHEND", "Neighbourhood of cannoli queues"],
    ["DUCKBOAT", "Amphibious ride, and a parade"],
    ["SWANBOAT", "Pedal-powered ride in the Public Garden"],
    ["ESPLANADE", "Riverside strip with the Hatch Shell"],
    ["MARATHON", "Third Monday in April, here"],
    ["BRUINS", "Team on the Garden ice"],
    ["CELTICS", "Team on the Garden parquet"],
  ],
  "arlington ma": [
    ["SPY", "___ Pond, beside the bike path"],
    ["POND", "Spy ___, frozen over in January"],
    ["AVE", "Mass ___, straight through the centre"],
    ["MASS", "___ Ave, the spine of the town"],
    ["TOWN", "What it is, having never become a city"],
    ["MYSTIC", "Lakes at the northern edge"],
    ["ROBBINS", "Name on the library and the farm"],
    ["CAPITOL", "The theatre on Mass Ave"],
    ["HEIGHTS", "The end of town up the hill"],
    ["MENOTOMY", "What the place was called in 1775"],
    ["MINUTEMAN", "Bike path on the old rail bed"],
    ["MEETING", "Town ___, how the place governs itself"],
  ],
  "quincy ma": [
    ["ADAMS", "Presidential family from here"],
    ["CLAM", "What the flats give up"],
    ["FORE", "___ River, and its shipyard"],
    ["RED", "___ Line, south to Braintree"],
    ["QUARRY", "Hole the granite came out of"],
    ["MARINA", "___ Bay, out on the water"],
    ["GRANITE", "What the hills were cut for"],
    ["HOUGHS", "___ Neck, on the harbour"],
    ["SHIPYARD", "Where the destroyers were built"],
    ["WOLLASTON", "Beach and stop of the same name"],
    ["MERRYMOUNT", "Park on the shore"],
  ],
  "big pharma": [
    ["FDA", "Agency that says yes or no"],
    ["DOSE", "How much the label says to take"],
    ["PILL", "The form most of it takes"],
    ["VIAL", "Small glass bottle from the fridge"],
    ["PHASE", "Trial stage, one through three"],
    ["TRIAL", "What phase three is"],
    ["ASSAY", "Bench test of potency"],
    ["LABEL", "Where the warnings live"],
    ["BRAND", "The expensive version"],
    ["COPAY", "Your share at the counter"],
    ["PBM", "Middleman between the plan and the pharmacy"],
    ["PATENT", "What the cliff is at the end of"],
    ["ORPHAN", "___ drug, for a rare disease"],
    ["REBATE", "What the middleman claws back"],
    ["RECALL", "Bad news from the factory"],
    ["GENERIC", "The cheap version, after the cliff"],
    ["PLACEBO", "The other arm of the trial"],
    ["BIOTECH", "The small end of the industry"],
    ["PIPELINE", "Everything still in development"],
    ["MOLECULE", "What the whole company rests on"],
  ],
  korea: [
    ["KPOP", "Seoul's biggest export"],
    ["WON", "Money in Seoul"],
    ["DMZ", "Strip between the two halves"],
    ["JEJU", "Volcanic island to the south"],
    ["SSAM", "Grilled meat wrapped in a leaf"],
    ["MANDU", "Dumpling, in Seoul"],
    ["TTEOK", "Chewy rice cake"],
    ["BUSAN", "Port city in the southeast"],
    ["HANOK", "House with the curved tiled roof"],
    ["HANBOK", "Bright traditional dress"],
    ["HANGUL", "Alphabet invented for the language"],
    ["GIMBAP", "Seaweed roll for the road"],
    ["BANCHAN", "Little dishes before the meal"],
    ["CHAEBOL", "Family conglomerate like Samsung"],
    ["BIBIMBAP", "Rice bowl mixed at the table"],
  ],
  vietnam: [
    ["HUE", "Old imperial capital"],
    ["TET", "Lunar new year holiday"],
    ["BANH", "___ mi, the baguette sandwich"],
    ["NUOC", "___ mam, the fish sauce"],
    ["MAM", "Nuoc ___"],
    ["CUON", "Goi ___, the fresh roll"],
    ["AODAI", "Long dress over trousers"],
    ["NONLA", "Conical hat"],
    ["HANOI", "Capital in the north"],
    ["MEKONG", "River of the southern delta"],
    ["HALONG", "Bay of limestone towers"],
    ["SAIGON", "What locals still call the big southern city"],
  ],
  reddit: [
    ["SUB", "One community on the site"],
    ["MOD", "Volunteer running it"],
    ["CROSSPOST", "The same thing, over in another sub"],
    ["AMA", "Ask me anything, in short"],
    ["TIL", "Today I learned, in short"],
    ["ELI", "___5: explain it simply"],
    ["KARMA", "Score that means nothing"],
    ["FLAIR", "Tag beside a username"],
    ["REPOST", "Seen it before"],
    ["LURKER", "Reader who never comments"],
  ],
  healthcare: [
    ["ICU", "Ward with the most monitors"],
    ["DISCHARGE", "Paperwork that lets you go home"],
    ["TRIAGE", "Deciding who is seen first"],
    ["INTAKE", "Paperwork on arrival"],
    ["ROUNDS", "The morning walk past the beds"],
    ["CHART", "Where it all gets written down"],
    ["REFER", "Send on to a specialist"],
    ["DEDUCTIBLE", "What you pay before the plan does"],
  ],
};

export const CLEM_EXTRA = {
  csharp: [
    ["ASYNC", "Keyword before a waiting method"],
    ["AWAIT", "What goes before the task"],
    ["LINQ", "Query syntax built into the language"],
    ["NUGET", "Where the packages come from"],
    ["ENUM", "Named set of constants"],
    ["VAR", "Let the compiler work out the type"],
    ["USING", "Line at the top, or a disposal block"],
    ["TASK", "What an asynchronous method returns"],
    ["NULL", "The billion-dollar mistake"],
    ["YIELD", "Keyword that makes an iterator"],
    ["STATIC", "Belonging to the type, not the instance"],
    ["SEALED", "Class nobody may inherit from"],
    ["STRUCT", "Value type, not a reference"],
    ["LAMBDA", "Little function written inline"],
    ["DOTNET", "The runtime it all sits on"],
    ["ROSLYN", "The compiler, by name"],
    ["BLAZOR", "Running it in the browser"],
    ["XUNIT", "One of the test frameworks"],
    ["MSBUILD", "What turns the project file into output"],
    ["NAMESPACE", "How the classes get organised"],
  ],
  "graphics cards": [
    ["VRAM", "Memory on the board itself"],
    ["GPU", "The chip you actually paid for"],
    ["CUDA", "Nvidia's compute toolkit"],
    ["RTX", "Prefix on the ray-tracing line"],
    ["GTX", "The line before that"],
    ["AMD", "The other one"],
    ["TDP", "Watts it is rated to shed"],
    ["FAN", "What spins up under load"],
    ["DIE", "The silicon itself"],
    ["RAY", "___ tracing, the expensive light"],
    ["DLSS", "Upscaling that invents the pixels"],
    ["FSR", "The open answer to that"],
    ["CLOCK", "Megahertz on the box"],
    ["BOOST", "Speed it reaches when it can"],
    ["SHADER", "Little program run per pixel"],
    ["RASTER", "The old way of drawing triangles"],
    ["TENSOR", "Core doing the matrix work"],
    ["CHIPLET", "Design made of smaller pieces"],
    ["THERMAL", "___ paste, between chip and cooler"],
    ["UNDERVOLT", "Trim the power, keep the speed"],
  ],
  "elden ring": [
    ["RANNI", "Witch of the blue moon"],
    ["MOHG", "Lord of blood in the underground"],
    ["RUNES", "What you drop where you died"],
    ["FLASK", "What you sip before the second phase"],
    ["ASHES", "Spirit summons in a jar"],
    ["GRACE", "Site of ___, the golden checkpoint"],
    ["ALTUS", "Plateau above the great lift"],
    ["CAELID", "Red, rotted region"],
    ["RADAHN", "Star-holding general on the sand"],
    ["MARGIT", "The fell omen at the first gate"],
    ["MELINA", "Guide who offers to be your maiden"],
    ["GODRICK", "The grafted one at Stormveil"],
    ["RENNALA", "Queen of the full moon"],
    ["TORRENT", "Your spectral steed"],
    ["ERDTREE", "Golden thing on the horizon"],
    ["MALENIA", "Blade of Miquella, undefeated"],
    ["LIMGRAVE", "Where every journey starts"],
    ["LEYNDELL", "The royal capital"],
    ["TARNISHED", "What you are"],
  ],
  "hospital data": [
    ["EMR", "The electronic chart, in short"],
    ["ICD", "Diagnosis code set"],
    ["CPT", "Procedure code set"],
    ["NPI", "A clinician's national number"],
    ["MRN", "How the chart is filed"],
    ["ADT", "Admit, discharge, transfer feed"],
    ["FHIR", "Modern standard for exchanging records"],
    ["LOS", "Length of stay, in short"],
    ["PHI", "The protected kind of information"],
    ["ETL", "Extract, transform, load"],
    ["CACHE", "The database under the old chart system"],
    ["AUDIT", "Trail showing who read what"],
    ["HIPAA", "Law behind all the privacy training"],
    ["COHORT", "The group the query pulled"],
    ["CENSUS", "How many beds are full right now"],
    ["METRIC", "The number on the dashboard"],
    ["CLARITY", "The reporting copy of the chart data"],
    ["READMIT", "Come back within thirty days"],
    ["REGISTRY", "Standing list of a condition's patients"],
    ["DASHBOARD", "Where the metrics land"],
  ],
  "magic the gathering": [
    ["MANA", "What lands make"],
    ["TAP", "Turn it sideways"],
    ["DECK", "Sixty cards, minimum"],
    ["BOLT", "Lightning ___, three damage for one"],
    ["MILL", "Win by emptying a library"],
    ["RAMP", "Get to the big spells early"],
    ["FOIL", "The shiny printing"],
    ["TOKEN", "Creature with no card"],
    ["FETCH", "Land that cracks for another"],
    ["WRATH", "Board wipe, classically"],
    ["DRAFT", "Pick one, pass the rest"],
    ["MODERN", "Format from the eighth edition on"],
    ["LEGACY", "Format where almost anything goes"],
    ["SORCERY", "Cast it on your own turn only"],
    ["INSTANT", "Cast it whenever you like"],
    ["COUNTER", "Say no to a spell"],
    ["BOOSTER", "Pack of fifteen"],
    ["ARTIFACT", "Colourless permanent"],
    ["CREATURE", "The thing that attacks"],
    ["MULLIGAN", "Shuffle back and draw one fewer"],
    ["COMMANDER", "Hundred-card format with a legend in charge"],
    ["SIDEBOARD", "Fifteen more for game two"],
  ],
  finance: [
    ["ROI", "What the spreadsheet is trying to show"],
    ["APR", "Rate on the loan, annualised"],
    ["EBITDA", "Earnings before all the awkward parts"],
    ["ACCRUAL", "Booked when earned, not when paid"],
    ["LEDGER", "Where the entries live"],
    ["HEDGE", "Position taken to offset another"],
    ["YIELD", "What the bond pays you"],
    ["SPREAD", "Gap between bid and ask"],
    ["MARGIN", "What is left after costs"],
    ["AUDIT", "Once-a-year unpleasantness"],
  ],
  sql: [
    ["CTE", "Common table expression, in short"],
    ["JOIN", "Bring two tables together"],
    ["NULL", "Neither equal nor unequal to anything"],
    ["INDEX", "What makes the lookup fast"],
    ["GROUP", "___ BY, before the aggregate"],
    ["HAVING", "The filter after the grouping"],
    ["UPSERT", "Insert, or update if it is there"],
    ["SCHEMA", "The shape of the database"],
    ["VACUUM", "Postgres housekeeping"],
    ["EXPLAIN", "Ask the planner what it will do"],
  ],
};

export const LORI_EXTRA = {
  costco: [
    ["BULK", "How everything is sold"],
    ["CART", "The flatbed kind, here"],
    ["GAS", "Cheapest thing in the parking lot"],
    ["CASE", "How the water arrives"],
    ["CLUB", "What the membership is to"],
    ["TIRE", "Centre that rotates them free"],
    ["AISLE", "Wide enough for two flatbeds"],
    ["HOTDOG", "Still a dollar fifty, with the soda"],
    ["CHURRO", "The other thing at the counter"],
    ["MUFFIN", "Sold six to a box, enormous"],
    ["PALLET", "What the boxes sit on"],
    ["SAMPLE", "Reason to do another lap"],
    ["KIRKLAND", "The house brand"],
    ["ROTISSERIE", "Chicken at the back of the store"],
  ],
  "pharma companies": [
    ["NOVO", "___ Nordisk, of the pens"],
    ["MERCK", "Rahway, New Jersey giant"],
    ["LILLY", "Indianapolis giant"],
    ["BAYER", "German maker of the original aspirin"],
    ["AMGEN", "Thousand Oaks biotech"],
    ["ROCHE", "Basel giant"],
    ["ASTRA", "___Zeneca, of Cambridge, England"],
    ["PFIZER", "New York giant"],
    ["SANOFI", "Paris giant"],
    ["TAKEDA", "Osaka giant"],
    ["BIOGEN", "Kendall Square neighbour"],
    ["VERTEX", "Seaport company built on cystic fibrosis"],
    ["GILEAD", "Foster City antiviral house"],
    ["ABBVIE", "Spun out of Abbott"],
    ["MODERNA", "Cambridge company of the vaccine"],
    ["NOVARTIS", "Basel's other giant"],
    ["REGENERON", "Tarrytown antibody house"],
  ],
  alnylam: [
    ["RNAI", "Interference the whole company rests on"],
    ["GENE", "What the therapy quiets"],
    ["ATTR", "Amyloidosis type in the pipeline"],
    ["SIRNA", "Small interfering strand"],
    ["LIVER", "Organ the doses are aimed at"],
    ["OXLUMO", "Treatment for a rare kidney stone disease"],
    ["LEQVIO", "Twice-a-year cholesterol injection"],
    ["KENDALL", "___ Square, the neighbourhood"],
    ["SILENCE", "What the therapy does to a gene"],
    ["ONPATTRO", "The first approved one"],
    ["AMVUTTRA", "The quarterly successor"],
  ],
  "leominster ma": [
    ["COMB", "What the city first made, in celluloid"],
    ["SEED", "Johnny Appleseed's other name part"],
    ["TWIN", "___ City, with Fitchburg"],
    ["ROUTE", "___ 2, running east to Boston"],
    ["WHALOM", "Amusement park that used to be here"],
    ["JOHNNY", "___ Appleseed, born in the town"],
    ["PLASTIC", "What the city calls itself the capital of"],
  ],
  "worcester ma": [
    ["WOO", "The city, to the students"],
    ["WPI", "The engineering school, in short"],
    ["CLARK", "University in Main South"],
    ["DINER", "Worcester Lunch Car product"],
    ["POLAR", "Seltzer made in the city"],
    ["CANAL", "___ District, downtown"],
    ["TABLE", "___ Talk, the little pies"],
    ["HANOVER", "Theatre downtown"],
    ["WORMTOWN", "The city's own nickname"],
    ["HOLYCROSS", "College on the hill"],
  ],
  iphone: [
    ["SIRI", "The one who mishears you"],
    ["APPS", "What fills the home screen"],
    ["USBC", "The port it finally got"],
    ["PRO", "The more expensive suffix"],
    ["MAX", "The bigger suffix"],
    ["FACEID", "Look to unlock"],
    ["ICLOUD", "Where the backup goes"],
    ["CAMERA", "Reason most people upgrade"],
    ["SILENT", "What the little switch sets"],
    ["AIRDROP", "Send it to the person next to you"],
    ["FACETIME", "Video call, on this brand"],
    ["IMESSAGE", "The blue bubbles"],
    ["PORTRAIT", "Mode that blurs the background"],
    ["LIGHTNING", "The port it used to have"],
  ],
  airpods: [
    ["ANC", "Noise cancelling, in short"],
    ["BUD", "One of the pair"],
    ["PODS", "The pair, informally"],
    ["STEM", "The part you squeeze"],
    ["TIPS", "Silicone ends, on the Pro"],
    ["PAIR", "What they do on opening the lid"],
    ["CASE", "Where they charge"],
    ["FINDMY", "How you locate the lost one"],
    ["SPATIAL", "Audio that follows your head"],
    ["TRANSPARENCY", "Mode that lets the room back in"],
  ],
  amex: [
    ["FEE", "The annual sting"],
    ["GOLD", "The card for restaurants"],
    ["SWIPE", "What the terminal wants"],
    ["TAP", "The contactless way"],
    ["POINTS", "Membership Rewards, plainly"],
    ["LOUNGE", "Centurion room at the airport"],
    ["OFFERS", "Deals you have to add to the card"],
    ["CREDIT", "The statement kind, monthly"],
    ["PLATINUM", "The metal one with the lounges"],
    ["CENTURION", "The invitation-only black one"],
  ],
  "chase reserve": [
    ["FEE", "What it costs a year"],
    ["METAL", "What the card is made of"],
    ["PORTAL", "Where the points book travel"],
    ["POINTS", "Ultimate Rewards, plainly"],
    ["LOUNGE", "Sapphire room, at a few airports"],
    ["ANNUAL", "Kind of fee it charges"],
    ["TRANSFER", "Move the points to an airline"],
    ["SAPPHIRE", "The card's own name"],
  ],
  "high end cards": [
    ["PERK", "Reason to keep paying the fee"],
    ["TIER", "Where the status sits"],
    ["MILES", "What the spending earns"],
    ["BLACK", "The invitation-only colour"],
    ["STATUS", "What the card hands you at check-in"],
    ["UPGRADE", "What the status might get you"],
    ["CONCIERGE", "The number on the back that books things"],
  ],
  "united airlines": [
    ["ORD", "The airline's Chicago hub"],
    ["EWR", "Its New Jersey hub"],
    ["SFO", "Its Bay Area hub"],
    ["DEN", "Its Denver code"],
    ["CLUB", "The lounge, by name"],
    ["SEAT", "What the app lets you change"],
    ["BOARD", "What group two does"],
    ["GROUP", "Boarding number called out"],
    ["POLARIS", "The business cabin"],
    ["PREMIER", "The status ladder"],
    ["MILEAGE", "___ Plus, the programme"],
    ["ECONOMY", "The back of the plane"],
  ],
  solidcore: [
    ["CORE", "What the whole class is about"],
    ["REPS", "How the coach counts it out"],
    ["BURN", "What the slow tempo produces"],
    ["PLANK", "Hold on the carriage"],
    ["LUNGE", "Split-stance move"],
    ["CLASS", "Fifty minutes of it"],
    ["COACH", "The one counting"],
    ["TEMPO", "Slow count that makes it hurt"],
    ["SPRING", "What sets the resistance"],
    ["LAGREE", "The method behind the machine"],
    ["REFORMER", "The sliding carriage machine"],
  ],
  travel: [
    ["TSA", "Line before the gate"],
    ["VISA", "Stamp you needed in advance"],
    ["REDEYE", "Overnight flight"],
    ["JETLAG", "What the first day is lost to"],
    ["HOSTEL", "Cheap bunk abroad"],
    ["CRUISE", "Holiday that comes with a cabin"],
    ["SAFARI", "Holiday with a game drive"],
    ["CUSTOMS", "Green channel or red"],
    ["CARRYON", "Bag that never leaves you"],
    ["LAYOVER", "The bit in the middle"],
    ["PASSPORT", "Blue book in the drawer"],
    ["ITINERARY", "The plan nobody sticks to"],
  ],
  instagram: [
    ["REEL", "Short vertical video"],
    ["GRID", "The nine squares of a profile"],
    ["FEED", "What you scroll"],
    ["TAG", "Name someone in the photo"],
    ["DMS", "The private inbox, in short"],
    ["LIKES", "The little hearts"],
    ["STORY", "Gone in a day"],
    ["FILTER", "What makes the sky bluer"],
    ["FOLLOW", "What the button asks for"],
    ["ARCHIVE", "Hide it without deleting it"],
    ["CAPTION", "Words under the picture"],
    ["EXPLORE", "The tab full of strangers"],
    ["HASHTAG", "Pound sign and a word"],
    ["CAROUSEL", "Swipe for the other photos"],
  ],
  yoga: [
    ["MAT", "What you unroll"],
    ["FLOW", "Sequence linked to the breath"],
    ["CROW", "Pose balanced on the hands"],
    ["ASANA", "Any one of the poses"],
    ["COBRA", "Chest-lifting pose on the front"],
    ["CHANT", "Sound held at the start"],
    ["BLOCK", "Foam help for tight hips"],
    ["STRAP", "Help for tight hamstrings"],
    ["CHILD", "___'s pose, the resting one"],
    ["HEATED", "Kind of room, at some studios"],
    ["BREATH", "What everything is timed to"],
    ["VINYASA", "The flowing style"],
    ["NAMASTE", "Word at the end"],
    ["WARRIOR", "Pose numbered one to three"],
    ["SAVASANA", "Lying still at the end"],
  ],
  vietnamese: [
    ["PHO", "The noodle soup"],
    ["BUN", "Rice noodle under the grilled pork"],
    ["COM", "Rice, on the menu"],
    ["CHA", "___ ca, the turmeric fish"],
    ["GOI", "___ cuon, the fresh roll"],
    ["CAPHE", "___ sua da, the iced coffee"],
    ["CHAO", "Rice porridge for a cold day"],
    ["THIT", "Meat, on the menu"],
  ],
  "interior design": [
    ["RUG", "What anchors the seating"],
    ["TILE", "What the backsplash is made of"],
    ["SOFA", "The big decision in the room"],
    ["TRIM", "Painted in the semi-gloss"],
    ["STAIN", "What goes on the wood instead of paint"],
    ["ACCENT", "The one bold wall"],
    ["SCONCE", "Light fixed to the wall"],
    ["RUNNER", "Long rug for a hall"],
    ["CHAISE", "Seat you can put your feet up on"],
    ["OTTOMAN", "Footstool that stores things"],
    ["SHIPLAP", "Horizontal boards, everywhere for a while"],
    ["PALETTE", "The three colours you settle on"],
    ["MOULDING", "Where the wall meets the ceiling"],
  ],
};
